INSERT INTO routing_cost (id, payment_method, fixed_fee, percentage_fee, authorization_rate, is_token) VALUES
                                                                                                           (1,  'VISA',       0.10, 0.0150, 0.98, false),
                                                                                                           (2,  'VISA',       0.08, 0.0130, 0.98, true),
                                                                                                           (3,  'MASTERCARD', 0.10, 0.0155, 0.97, false),
                                                                                                           (4,  'MASTERCARD', 0.08, 0.0135, 0.97, true),
                                                                                                           (5,  'AMEX',       0.15, 0.0250, 0.95, false),
                                                                                                           (6,  'AMEX',       0.12, 0.0220, 0.95, true),
                                                                                                           (7,  'DISCOVER',   0.10, 0.0140, 0.96, false),
                                                                                                           (8,  'DISCOVER',   0.08, 0.0120, 0.96, true),
                                                                                                           (9,  'MAESTRO',    0.08, 0.0120, 0.96, false),
                                                                                                           (10, 'MAESTRO',    0.06, 0.0100, 0.96, true),
                                                                                                           (11, 'ACCEL',      0.05, 0.0080, 0.99, false),
                                                                                                           (12, 'STAR',       0.05, 0.0080, 0.99, false),
                                                                                                           (13, 'NYCE',       0.05, 0.0075, 0.99, false),
                                                                                                           (14, 'PULSE',      0.05, 0.0075, 0.99, false);
