/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AuthorizationCompletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4634143828524575826L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AuthorizationCompletedEvent\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"paymentId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"success\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"authCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"rrn\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"processorTransactionId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"selectedPaymentMethod\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"PaymentMethodEnum\",\"symbols\":[\"VISA\",\"MASTERCARD\",\"AMEX\",\"DISCOVER\",\"ACCEL\",\"STAR\",\"NYCE\",\"PULSE\",\"MAESTRO\"]}],\"default\":null},{\"name\":\"errorMessage\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"timestamp\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AuthorizationCompletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AuthorizationCompletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AuthorizationCompletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AuthorizationCompletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AuthorizationCompletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AuthorizationCompletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AuthorizationCompletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AuthorizationCompletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AuthorizationCompletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence paymentId;
  private java.lang.Boolean success;
  private java.lang.CharSequence authCode;
  private java.lang.CharSequence rrn;
  private java.lang.CharSequence processorTransactionId;
  private com.zaheudev.shared.avro.PaymentMethodEnum selectedPaymentMethod;
  private java.lang.CharSequence errorMessage;
  private java.lang.Long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AuthorizationCompletedEvent() {}

  /**
   * All-args constructor.
   * @param paymentId The new value for paymentId
   * @param success The new value for success
   * @param authCode The new value for authCode
   * @param rrn The new value for rrn
   * @param processorTransactionId The new value for processorTransactionId
   * @param selectedPaymentMethod The new value for selectedPaymentMethod
   * @param errorMessage The new value for errorMessage
   * @param timestamp The new value for timestamp
   */
  public AuthorizationCompletedEvent(java.lang.CharSequence paymentId, java.lang.Boolean success, java.lang.CharSequence authCode, java.lang.CharSequence rrn, java.lang.CharSequence processorTransactionId, com.zaheudev.shared.avro.PaymentMethodEnum selectedPaymentMethod, java.lang.CharSequence errorMessage, java.lang.Long timestamp) {
    this.paymentId = paymentId;
    this.success = success;
    this.authCode = authCode;
    this.rrn = rrn;
    this.processorTransactionId = processorTransactionId;
    this.selectedPaymentMethod = selectedPaymentMethod;
    this.errorMessage = errorMessage;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return success;
    case 2: return authCode;
    case 3: return rrn;
    case 4: return processorTransactionId;
    case 5: return selectedPaymentMethod;
    case 6: return errorMessage;
    case 7: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: success = (java.lang.Boolean)value$; break;
    case 2: authCode = (java.lang.CharSequence)value$; break;
    case 3: rrn = (java.lang.CharSequence)value$; break;
    case 4: processorTransactionId = (java.lang.CharSequence)value$; break;
    case 5: selectedPaymentMethod = (com.zaheudev.shared.avro.PaymentMethodEnum)value$; break;
    case 6: errorMessage = (java.lang.CharSequence)value$; break;
    case 7: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'success' field.
   * @return The value of the 'success' field.
   */
  public java.lang.Boolean getSuccess() {
    return success;
  }


  /**
   * Sets the value of the 'success' field.
   * @param value the value to set.
   */
  public void setSuccess(java.lang.Boolean value) {
    this.success = value;
  }

  /**
   * Gets the value of the 'authCode' field.
   * @return The value of the 'authCode' field.
   */
  public java.lang.CharSequence getAuthCode() {
    return authCode;
  }


  /**
   * Sets the value of the 'authCode' field.
   * @param value the value to set.
   */
  public void setAuthCode(java.lang.CharSequence value) {
    this.authCode = value;
  }

  /**
   * Gets the value of the 'rrn' field.
   * @return The value of the 'rrn' field.
   */
  public java.lang.CharSequence getRrn() {
    return rrn;
  }


  /**
   * Sets the value of the 'rrn' field.
   * @param value the value to set.
   */
  public void setRrn(java.lang.CharSequence value) {
    this.rrn = value;
  }

  /**
   * Gets the value of the 'processorTransactionId' field.
   * @return The value of the 'processorTransactionId' field.
   */
  public java.lang.CharSequence getProcessorTransactionId() {
    return processorTransactionId;
  }


  /**
   * Sets the value of the 'processorTransactionId' field.
   * @param value the value to set.
   */
  public void setProcessorTransactionId(java.lang.CharSequence value) {
    this.processorTransactionId = value;
  }

  /**
   * Gets the value of the 'selectedPaymentMethod' field.
   * @return The value of the 'selectedPaymentMethod' field.
   */
  public com.zaheudev.shared.avro.PaymentMethodEnum getSelectedPaymentMethod() {
    return selectedPaymentMethod;
  }


  /**
   * Sets the value of the 'selectedPaymentMethod' field.
   * @param value the value to set.
   */
  public void setSelectedPaymentMethod(com.zaheudev.shared.avro.PaymentMethodEnum value) {
    this.selectedPaymentMethod = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.CharSequence getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.CharSequence value) {
    this.errorMessage = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new AuthorizationCompletedEvent RecordBuilder.
   * @return A new AuthorizationCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder newBuilder() {
    return new com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder();
  }

  /**
   * Creates a new AuthorizationCompletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AuthorizationCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder newBuilder(com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new AuthorizationCompletedEvent RecordBuilder by copying an existing AuthorizationCompletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new AuthorizationCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder newBuilder(com.zaheudev.shared.avro.AuthorizationCompletedEvent other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AuthorizationCompletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AuthorizationCompletedEvent>
    implements org.apache.avro.data.RecordBuilder<AuthorizationCompletedEvent> {

    private java.lang.CharSequence paymentId;
    private java.lang.Boolean success;
    private java.lang.CharSequence authCode;
    private java.lang.CharSequence rrn;
    private java.lang.CharSequence processorTransactionId;
    private com.zaheudev.shared.avro.PaymentMethodEnum selectedPaymentMethod;
    private java.lang.CharSequence errorMessage;
    private java.lang.Long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.success)) {
        this.success = data().deepCopy(fields()[1].schema(), other.success);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.authCode)) {
        this.authCode = data().deepCopy(fields()[2].schema(), other.authCode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.rrn)) {
        this.rrn = data().deepCopy(fields()[3].schema(), other.rrn);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.processorTransactionId)) {
        this.processorTransactionId = data().deepCopy(fields()[4].schema(), other.processorTransactionId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.selectedPaymentMethod)) {
        this.selectedPaymentMethod = data().deepCopy(fields()[5].schema(), other.selectedPaymentMethod);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[6].schema(), other.errorMessage);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing AuthorizationCompletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.AuthorizationCompletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.success)) {
        this.success = data().deepCopy(fields()[1].schema(), other.success);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.authCode)) {
        this.authCode = data().deepCopy(fields()[2].schema(), other.authCode);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.rrn)) {
        this.rrn = data().deepCopy(fields()[3].schema(), other.rrn);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.processorTransactionId)) {
        this.processorTransactionId = data().deepCopy(fields()[4].schema(), other.processorTransactionId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.selectedPaymentMethod)) {
        this.selectedPaymentMethod = data().deepCopy(fields()[5].schema(), other.selectedPaymentMethod);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[6].schema(), other.errorMessage);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'success' field.
      * @return The value.
      */
    public java.lang.Boolean getSuccess() {
      return success;
    }


    /**
      * Sets the value of the 'success' field.
      * @param value The value of 'success'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder setSuccess(java.lang.Boolean value) {
      validate(fields()[1], value);
      this.success = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'success' field has been set.
      * @return True if the 'success' field has been set, false otherwise.
      */
    public boolean hasSuccess() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'success' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder clearSuccess() {
      success = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'authCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getAuthCode() {
      return authCode;
    }


    /**
      * Sets the value of the 'authCode' field.
      * @param value The value of 'authCode'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder setAuthCode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.authCode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'authCode' field has been set.
      * @return True if the 'authCode' field has been set, false otherwise.
      */
    public boolean hasAuthCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'authCode' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder clearAuthCode() {
      authCode = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'rrn' field.
      * @return The value.
      */
    public java.lang.CharSequence getRrn() {
      return rrn;
    }


    /**
      * Sets the value of the 'rrn' field.
      * @param value The value of 'rrn'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder setRrn(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.rrn = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'rrn' field has been set.
      * @return True if the 'rrn' field has been set, false otherwise.
      */
    public boolean hasRrn() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'rrn' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder clearRrn() {
      rrn = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'processorTransactionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProcessorTransactionId() {
      return processorTransactionId;
    }


    /**
      * Sets the value of the 'processorTransactionId' field.
      * @param value The value of 'processorTransactionId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder setProcessorTransactionId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.processorTransactionId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'processorTransactionId' field has been set.
      * @return True if the 'processorTransactionId' field has been set, false otherwise.
      */
    public boolean hasProcessorTransactionId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'processorTransactionId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder clearProcessorTransactionId() {
      processorTransactionId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'selectedPaymentMethod' field.
      * @return The value.
      */
    public com.zaheudev.shared.avro.PaymentMethodEnum getSelectedPaymentMethod() {
      return selectedPaymentMethod;
    }


    /**
      * Sets the value of the 'selectedPaymentMethod' field.
      * @param value The value of 'selectedPaymentMethod'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder setSelectedPaymentMethod(com.zaheudev.shared.avro.PaymentMethodEnum value) {
      validate(fields()[5], value);
      this.selectedPaymentMethod = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'selectedPaymentMethod' field has been set.
      * @return True if the 'selectedPaymentMethod' field has been set, false otherwise.
      */
    public boolean hasSelectedPaymentMethod() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'selectedPaymentMethod' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder clearSelectedPaymentMethod() {
      selectedPaymentMethod = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.CharSequence getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder setErrorMessage(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.errorMessage = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder setTimestamp(java.lang.Long value) {
      validate(fields()[7], value);
      this.timestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationCompletedEvent.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AuthorizationCompletedEvent build() {
      try {
        AuthorizationCompletedEvent record = new AuthorizationCompletedEvent();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.success = fieldSetFlags()[1] ? this.success : (java.lang.Boolean) defaultValue(fields()[1]);
        record.authCode = fieldSetFlags()[2] ? this.authCode : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.rrn = fieldSetFlags()[3] ? this.rrn : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.processorTransactionId = fieldSetFlags()[4] ? this.processorTransactionId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.selectedPaymentMethod = fieldSetFlags()[5] ? this.selectedPaymentMethod : (com.zaheudev.shared.avro.PaymentMethodEnum) defaultValue(fields()[5]);
        record.errorMessage = fieldSetFlags()[6] ? this.errorMessage : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.timestamp = fieldSetFlags()[7] ? this.timestamp : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AuthorizationCompletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AuthorizationCompletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AuthorizationCompletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<AuthorizationCompletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.paymentId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.paymentId);
    }

    if (this.success == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.success);
    }

    if (this.authCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.authCode);
    }

    if (this.rrn == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.rrn);
    }

    if (this.processorTransactionId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.processorTransactionId);
    }

    if (this.selectedPaymentMethod == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.selectedPaymentMethod.ordinal());
    }

    if (this.errorMessage == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.errorMessage);
    }

    if (this.timestamp == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.timestamp);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.paymentId = null;
      } else {
        this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.success = null;
      } else {
        this.success = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.authCode = null;
      } else {
        this.authCode = in.readString(this.authCode instanceof Utf8 ? (Utf8)this.authCode : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.rrn = null;
      } else {
        this.rrn = in.readString(this.rrn instanceof Utf8 ? (Utf8)this.rrn : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.processorTransactionId = null;
      } else {
        this.processorTransactionId = in.readString(this.processorTransactionId instanceof Utf8 ? (Utf8)this.processorTransactionId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.selectedPaymentMethod = null;
      } else {
        this.selectedPaymentMethod = com.zaheudev.shared.avro.PaymentMethodEnum.values()[in.readEnum()];
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.errorMessage = null;
      } else {
        this.errorMessage = in.readString(this.errorMessage instanceof Utf8 ? (Utf8)this.errorMessage : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.timestamp = null;
      } else {
        this.timestamp = in.readLong();
      }

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.paymentId = null;
          } else {
            this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.success = null;
          } else {
            this.success = in.readBoolean();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.authCode = null;
          } else {
            this.authCode = in.readString(this.authCode instanceof Utf8 ? (Utf8)this.authCode : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.rrn = null;
          } else {
            this.rrn = in.readString(this.rrn instanceof Utf8 ? (Utf8)this.rrn : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.processorTransactionId = null;
          } else {
            this.processorTransactionId = in.readString(this.processorTransactionId instanceof Utf8 ? (Utf8)this.processorTransactionId : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.selectedPaymentMethod = null;
          } else {
            this.selectedPaymentMethod = com.zaheudev.shared.avro.PaymentMethodEnum.values()[in.readEnum()];
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.errorMessage = null;
          } else {
            this.errorMessage = in.readString(this.errorMessage instanceof Utf8 ? (Utf8)this.errorMessage : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.timestamp = null;
          } else {
            this.timestamp = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (success == null ? 0 : success.hashCode());
    result = 31 * result + (authCode == null ? 0 : authCode.hashCode());
    result = 31 * result + (rrn == null ? 0 : rrn.hashCode());
    result = 31 * result + (processorTransactionId == null ? 0 : processorTransactionId.hashCode());
    result = 31 * result + (selectedPaymentMethod == null ? 0 : ((java.lang.Enum) selectedPaymentMethod).ordinal());
    result = 31 * result + (errorMessage == null ? 0 : errorMessage.hashCode());
    result = 31 * result + (timestamp == null ? 0 : timestamp.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof AuthorizationCompletedEvent)) {
      return false;
    }
    AuthorizationCompletedEvent other = (AuthorizationCompletedEvent) o;
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.success, other.success)) {
      return false;
    }
    if (Utf8.compareSequences(this.authCode, other.authCode) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.rrn, other.rrn) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.processorTransactionId, other.processorTransactionId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.selectedPaymentMethod, other.selectedPaymentMethod)) {
      return false;
    }
    if (Utf8.compareSequences(this.errorMessage, other.errorMessage) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.timestamp, other.timestamp)) {
      return false;
    }
    return true;
  }
}










