/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This is used to request an authorization for CNE module */
@org.apache.avro.specific.AvroGenerated
public class AuthorizationRequested extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7789272759348479981L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AuthorizationRequested\",\"namespace\":\"com.zaheudev.shared.avro\",\"doc\":\"This is used to request an authorization for CNE module\",\"fields\":[{\"name\":\"paymentId\",\"type\":\"string\"},{\"name\":\"tokenRef\",\"type\":\"string\"},{\"name\":\"merchantRef\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AuthorizationRequested> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AuthorizationRequested> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AuthorizationRequested> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AuthorizationRequested> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AuthorizationRequested> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AuthorizationRequested to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AuthorizationRequested from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AuthorizationRequested instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AuthorizationRequested fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence paymentId;
  private java.lang.CharSequence tokenRef;
  private java.lang.CharSequence merchantRef;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AuthorizationRequested() {}

  /**
   * All-args constructor.
   * @param paymentId The new value for paymentId
   * @param tokenRef The new value for tokenRef
   * @param merchantRef The new value for merchantRef
   */
  public AuthorizationRequested(java.lang.CharSequence paymentId, java.lang.CharSequence tokenRef, java.lang.CharSequence merchantRef) {
    this.paymentId = paymentId;
    this.tokenRef = tokenRef;
    this.merchantRef = merchantRef;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return tokenRef;
    case 2: return merchantRef;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: tokenRef = (java.lang.CharSequence)value$; break;
    case 2: merchantRef = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'tokenRef' field.
   * @return The value of the 'tokenRef' field.
   */
  public java.lang.CharSequence getTokenRef() {
    return tokenRef;
  }


  /**
   * Sets the value of the 'tokenRef' field.
   * @param value the value to set.
   */
  public void setTokenRef(java.lang.CharSequence value) {
    this.tokenRef = value;
  }

  /**
   * Gets the value of the 'merchantRef' field.
   * @return The value of the 'merchantRef' field.
   */
  public java.lang.CharSequence getMerchantRef() {
    return merchantRef;
  }


  /**
   * Sets the value of the 'merchantRef' field.
   * @param value the value to set.
   */
  public void setMerchantRef(java.lang.CharSequence value) {
    this.merchantRef = value;
  }

  /**
   * Creates a new AuthorizationRequested RecordBuilder.
   * @return A new AuthorizationRequested RecordBuilder
   */
  public static com.zaheudev.shared.avro.AuthorizationRequested.Builder newBuilder() {
    return new com.zaheudev.shared.avro.AuthorizationRequested.Builder();
  }

  /**
   * Creates a new AuthorizationRequested RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AuthorizationRequested RecordBuilder
   */
  public static com.zaheudev.shared.avro.AuthorizationRequested.Builder newBuilder(com.zaheudev.shared.avro.AuthorizationRequested.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.AuthorizationRequested.Builder();
    } else {
      return new com.zaheudev.shared.avro.AuthorizationRequested.Builder(other);
    }
  }

  /**
   * Creates a new AuthorizationRequested RecordBuilder by copying an existing AuthorizationRequested instance.
   * @param other The existing instance to copy.
   * @return A new AuthorizationRequested RecordBuilder
   */
  public static com.zaheudev.shared.avro.AuthorizationRequested.Builder newBuilder(com.zaheudev.shared.avro.AuthorizationRequested other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.AuthorizationRequested.Builder();
    } else {
      return new com.zaheudev.shared.avro.AuthorizationRequested.Builder(other);
    }
  }

  /**
   * RecordBuilder for AuthorizationRequested instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AuthorizationRequested>
    implements org.apache.avro.data.RecordBuilder<AuthorizationRequested> {

    private java.lang.CharSequence paymentId;
    private java.lang.CharSequence tokenRef;
    private java.lang.CharSequence merchantRef;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.AuthorizationRequested.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tokenRef)) {
        this.tokenRef = data().deepCopy(fields()[1].schema(), other.tokenRef);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.merchantRef)) {
        this.merchantRef = data().deepCopy(fields()[2].schema(), other.merchantRef);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AuthorizationRequested instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.AuthorizationRequested other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tokenRef)) {
        this.tokenRef = data().deepCopy(fields()[1].schema(), other.tokenRef);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.merchantRef)) {
        this.merchantRef = data().deepCopy(fields()[2].schema(), other.merchantRef);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationRequested.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationRequested.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tokenRef' field.
      * @return The value.
      */
    public java.lang.CharSequence getTokenRef() {
      return tokenRef;
    }


    /**
      * Sets the value of the 'tokenRef' field.
      * @param value The value of 'tokenRef'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationRequested.Builder setTokenRef(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.tokenRef = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tokenRef' field has been set.
      * @return True if the 'tokenRef' field has been set, false otherwise.
      */
    public boolean hasTokenRef() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tokenRef' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationRequested.Builder clearTokenRef() {
      tokenRef = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchantRef' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantRef() {
      return merchantRef;
    }


    /**
      * Sets the value of the 'merchantRef' field.
      * @param value The value of 'merchantRef'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationRequested.Builder setMerchantRef(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.merchantRef = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantRef' field has been set.
      * @return True if the 'merchantRef' field has been set, false otherwise.
      */
    public boolean hasMerchantRef() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'merchantRef' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.AuthorizationRequested.Builder clearMerchantRef() {
      merchantRef = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AuthorizationRequested build() {
      try {
        AuthorizationRequested record = new AuthorizationRequested();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tokenRef = fieldSetFlags()[1] ? this.tokenRef : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.merchantRef = fieldSetFlags()[2] ? this.merchantRef : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AuthorizationRequested>
    WRITER$ = (org.apache.avro.io.DatumWriter<AuthorizationRequested>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AuthorizationRequested>
    READER$ = (org.apache.avro.io.DatumReader<AuthorizationRequested>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentId);

    out.writeString(this.tokenRef);

    out.writeString(this.merchantRef);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);

      this.tokenRef = in.readString(this.tokenRef instanceof Utf8 ? (Utf8)this.tokenRef : null);

      this.merchantRef = in.readString(this.merchantRef instanceof Utf8 ? (Utf8)this.merchantRef : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          break;

        case 1:
          this.tokenRef = in.readString(this.tokenRef instanceof Utf8 ? (Utf8)this.tokenRef : null);
          break;

        case 2:
          this.merchantRef = in.readString(this.merchantRef instanceof Utf8 ? (Utf8)this.merchantRef : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (tokenRef == null ? 0 : tokenRef.hashCode());
    result = 31 * result + (merchantRef == null ? 0 : merchantRef.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof AuthorizationRequested)) {
      return false;
    }
    AuthorizationRequested other = (AuthorizationRequested) o;
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.tokenRef, other.tokenRef) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.merchantRef, other.merchantRef) != 0) {
      return false;
    }
    return true;
  }
}










