/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CardRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7636729632220163405L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CardRecord\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"tokenRef\",\"type\":\"string\",\"doc\":\"This is the token for the card details\"},{\"name\":\"bin\",\"type\":\"string\",\"doc\":\"The first 6 digits of the card number\"},{\"name\":\"lastFour\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CardRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CardRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CardRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CardRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CardRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CardRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CardRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CardRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CardRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** This is the token for the card details */
  private java.lang.CharSequence tokenRef;
  /** The first 6 digits of the card number */
  private java.lang.CharSequence bin;
  private java.lang.CharSequence lastFour;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CardRecord() {}

  /**
   * All-args constructor.
   * @param tokenRef This is the token for the card details
   * @param bin The first 6 digits of the card number
   * @param lastFour The new value for lastFour
   */
  public CardRecord(java.lang.CharSequence tokenRef, java.lang.CharSequence bin, java.lang.CharSequence lastFour) {
    this.tokenRef = tokenRef;
    this.bin = bin;
    this.lastFour = lastFour;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tokenRef;
    case 1: return bin;
    case 2: return lastFour;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tokenRef = (java.lang.CharSequence)value$; break;
    case 1: bin = (java.lang.CharSequence)value$; break;
    case 2: lastFour = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tokenRef' field.
   * @return This is the token for the card details
   */
  public java.lang.CharSequence getTokenRef() {
    return tokenRef;
  }


  /**
   * Sets the value of the 'tokenRef' field.
   * This is the token for the card details
   * @param value the value to set.
   */
  public void setTokenRef(java.lang.CharSequence value) {
    this.tokenRef = value;
  }

  /**
   * Gets the value of the 'bin' field.
   * @return The first 6 digits of the card number
   */
  public java.lang.CharSequence getBin() {
    return bin;
  }


  /**
   * Sets the value of the 'bin' field.
   * The first 6 digits of the card number
   * @param value the value to set.
   */
  public void setBin(java.lang.CharSequence value) {
    this.bin = value;
  }

  /**
   * Gets the value of the 'lastFour' field.
   * @return The value of the 'lastFour' field.
   */
  public java.lang.CharSequence getLastFour() {
    return lastFour;
  }


  /**
   * Sets the value of the 'lastFour' field.
   * @param value the value to set.
   */
  public void setLastFour(java.lang.CharSequence value) {
    this.lastFour = value;
  }

  /**
   * Creates a new CardRecord RecordBuilder.
   * @return A new CardRecord RecordBuilder
   */
  public static com.zaheudev.shared.avro.CardRecord.Builder newBuilder() {
    return new com.zaheudev.shared.avro.CardRecord.Builder();
  }

  /**
   * Creates a new CardRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CardRecord RecordBuilder
   */
  public static com.zaheudev.shared.avro.CardRecord.Builder newBuilder(com.zaheudev.shared.avro.CardRecord.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.CardRecord.Builder();
    } else {
      return new com.zaheudev.shared.avro.CardRecord.Builder(other);
    }
  }

  /**
   * Creates a new CardRecord RecordBuilder by copying an existing CardRecord instance.
   * @param other The existing instance to copy.
   * @return A new CardRecord RecordBuilder
   */
  public static com.zaheudev.shared.avro.CardRecord.Builder newBuilder(com.zaheudev.shared.avro.CardRecord other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.CardRecord.Builder();
    } else {
      return new com.zaheudev.shared.avro.CardRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for CardRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CardRecord>
    implements org.apache.avro.data.RecordBuilder<CardRecord> {

    /** This is the token for the card details */
    private java.lang.CharSequence tokenRef;
    /** The first 6 digits of the card number */
    private java.lang.CharSequence bin;
    private java.lang.CharSequence lastFour;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.CardRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tokenRef)) {
        this.tokenRef = data().deepCopy(fields()[0].schema(), other.tokenRef);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bin)) {
        this.bin = data().deepCopy(fields()[1].schema(), other.bin);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastFour)) {
        this.lastFour = data().deepCopy(fields()[2].schema(), other.lastFour);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CardRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.CardRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.tokenRef)) {
        this.tokenRef = data().deepCopy(fields()[0].schema(), other.tokenRef);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bin)) {
        this.bin = data().deepCopy(fields()[1].schema(), other.bin);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastFour)) {
        this.lastFour = data().deepCopy(fields()[2].schema(), other.lastFour);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'tokenRef' field.
      * This is the token for the card details
      * @return The value.
      */
    public java.lang.CharSequence getTokenRef() {
      return tokenRef;
    }


    /**
      * Sets the value of the 'tokenRef' field.
      * This is the token for the card details
      * @param value The value of 'tokenRef'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardRecord.Builder setTokenRef(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tokenRef = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tokenRef' field has been set.
      * This is the token for the card details
      * @return True if the 'tokenRef' field has been set, false otherwise.
      */
    public boolean hasTokenRef() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tokenRef' field.
      * This is the token for the card details
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardRecord.Builder clearTokenRef() {
      tokenRef = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bin' field.
      * The first 6 digits of the card number
      * @return The value.
      */
    public java.lang.CharSequence getBin() {
      return bin;
    }


    /**
      * Sets the value of the 'bin' field.
      * The first 6 digits of the card number
      * @param value The value of 'bin'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardRecord.Builder setBin(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.bin = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bin' field has been set.
      * The first 6 digits of the card number
      * @return True if the 'bin' field has been set, false otherwise.
      */
    public boolean hasBin() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bin' field.
      * The first 6 digits of the card number
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardRecord.Builder clearBin() {
      bin = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastFour' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastFour() {
      return lastFour;
    }


    /**
      * Sets the value of the 'lastFour' field.
      * @param value The value of 'lastFour'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardRecord.Builder setLastFour(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastFour = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastFour' field has been set.
      * @return True if the 'lastFour' field has been set, false otherwise.
      */
    public boolean hasLastFour() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastFour' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardRecord.Builder clearLastFour() {
      lastFour = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CardRecord build() {
      try {
        CardRecord record = new CardRecord();
        record.tokenRef = fieldSetFlags()[0] ? this.tokenRef : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.bin = fieldSetFlags()[1] ? this.bin : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastFour = fieldSetFlags()[2] ? this.lastFour : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CardRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<CardRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CardRecord>
    READER$ = (org.apache.avro.io.DatumReader<CardRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tokenRef);

    out.writeString(this.bin);

    out.writeString(this.lastFour);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tokenRef = in.readString(this.tokenRef instanceof Utf8 ? (Utf8)this.tokenRef : null);

      this.bin = in.readString(this.bin instanceof Utf8 ? (Utf8)this.bin : null);

      this.lastFour = in.readString(this.lastFour instanceof Utf8 ? (Utf8)this.lastFour : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tokenRef = in.readString(this.tokenRef instanceof Utf8 ? (Utf8)this.tokenRef : null);
          break;

        case 1:
          this.bin = in.readString(this.bin instanceof Utf8 ? (Utf8)this.bin : null);
          break;

        case 2:
          this.lastFour = in.readString(this.lastFour instanceof Utf8 ? (Utf8)this.lastFour : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (tokenRef == null ? 0 : tokenRef.hashCode());
    result = 31 * result + (bin == null ? 0 : bin.hashCode());
    result = 31 * result + (lastFour == null ? 0 : lastFour.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof CardRecord)) {
      return false;
    }
    CardRecord other = (CardRecord) o;
    if (Utf8.compareSequences(this.tokenRef, other.tokenRef) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.bin, other.bin) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.lastFour, other.lastFour) != 0) {
      return false;
    }
    return true;
  }
}










