/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CardDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8103031620504169284L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CardDetails\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"bin\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"cardHolderName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"expiryMonth\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"expiryYear\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"cvv\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CardDetails> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CardDetails> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CardDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CardDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CardDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CardDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CardDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CardDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CardDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence bin;
  private java.lang.CharSequence cardHolderName;
  private java.lang.CharSequence expiryMonth;
  private java.lang.CharSequence expiryYear;
  private java.lang.CharSequence cvv;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CardDetails() {}

  /**
   * All-args constructor.
   * @param bin The new value for bin
   * @param cardHolderName The new value for cardHolderName
   * @param expiryMonth The new value for expiryMonth
   * @param expiryYear The new value for expiryYear
   * @param cvv The new value for cvv
   */
  public CardDetails(java.lang.CharSequence bin, java.lang.CharSequence cardHolderName, java.lang.CharSequence expiryMonth, java.lang.CharSequence expiryYear, java.lang.CharSequence cvv) {
    this.bin = bin;
    this.cardHolderName = cardHolderName;
    this.expiryMonth = expiryMonth;
    this.expiryYear = expiryYear;
    this.cvv = cvv;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bin;
    case 1: return cardHolderName;
    case 2: return expiryMonth;
    case 3: return expiryYear;
    case 4: return cvv;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bin = (java.lang.CharSequence)value$; break;
    case 1: cardHolderName = (java.lang.CharSequence)value$; break;
    case 2: expiryMonth = (java.lang.CharSequence)value$; break;
    case 3: expiryYear = (java.lang.CharSequence)value$; break;
    case 4: cvv = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bin' field.
   * @return The value of the 'bin' field.
   */
  public java.lang.CharSequence getBin() {
    return bin;
  }


  /**
   * Sets the value of the 'bin' field.
   * @param value the value to set.
   */
  public void setBin(java.lang.CharSequence value) {
    this.bin = value;
  }

  /**
   * Gets the value of the 'cardHolderName' field.
   * @return The value of the 'cardHolderName' field.
   */
  public java.lang.CharSequence getCardHolderName() {
    return cardHolderName;
  }


  /**
   * Sets the value of the 'cardHolderName' field.
   * @param value the value to set.
   */
  public void setCardHolderName(java.lang.CharSequence value) {
    this.cardHolderName = value;
  }

  /**
   * Gets the value of the 'expiryMonth' field.
   * @return The value of the 'expiryMonth' field.
   */
  public java.lang.CharSequence getExpiryMonth() {
    return expiryMonth;
  }


  /**
   * Sets the value of the 'expiryMonth' field.
   * @param value the value to set.
   */
  public void setExpiryMonth(java.lang.CharSequence value) {
    this.expiryMonth = value;
  }

  /**
   * Gets the value of the 'expiryYear' field.
   * @return The value of the 'expiryYear' field.
   */
  public java.lang.CharSequence getExpiryYear() {
    return expiryYear;
  }


  /**
   * Sets the value of the 'expiryYear' field.
   * @param value the value to set.
   */
  public void setExpiryYear(java.lang.CharSequence value) {
    this.expiryYear = value;
  }

  /**
   * Gets the value of the 'cvv' field.
   * @return The value of the 'cvv' field.
   */
  public java.lang.CharSequence getCvv() {
    return cvv;
  }


  /**
   * Sets the value of the 'cvv' field.
   * @param value the value to set.
   */
  public void setCvv(java.lang.CharSequence value) {
    this.cvv = value;
  }

  /**
   * Creates a new CardDetails RecordBuilder.
   * @return A new CardDetails RecordBuilder
   */
  public static com.zaheudev.shared.avro.CardDetails.Builder newBuilder() {
    return new com.zaheudev.shared.avro.CardDetails.Builder();
  }

  /**
   * Creates a new CardDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CardDetails RecordBuilder
   */
  public static com.zaheudev.shared.avro.CardDetails.Builder newBuilder(com.zaheudev.shared.avro.CardDetails.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.CardDetails.Builder();
    } else {
      return new com.zaheudev.shared.avro.CardDetails.Builder(other);
    }
  }

  /**
   * Creates a new CardDetails RecordBuilder by copying an existing CardDetails instance.
   * @param other The existing instance to copy.
   * @return A new CardDetails RecordBuilder
   */
  public static com.zaheudev.shared.avro.CardDetails.Builder newBuilder(com.zaheudev.shared.avro.CardDetails other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.CardDetails.Builder();
    } else {
      return new com.zaheudev.shared.avro.CardDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for CardDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CardDetails>
    implements org.apache.avro.data.RecordBuilder<CardDetails> {

    private java.lang.CharSequence bin;
    private java.lang.CharSequence cardHolderName;
    private java.lang.CharSequence expiryMonth;
    private java.lang.CharSequence expiryYear;
    private java.lang.CharSequence cvv;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.CardDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bin)) {
        this.bin = data().deepCopy(fields()[0].schema(), other.bin);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.cardHolderName)) {
        this.cardHolderName = data().deepCopy(fields()[1].schema(), other.cardHolderName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.expiryMonth)) {
        this.expiryMonth = data().deepCopy(fields()[2].schema(), other.expiryMonth);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.expiryYear)) {
        this.expiryYear = data().deepCopy(fields()[3].schema(), other.expiryYear);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.cvv)) {
        this.cvv = data().deepCopy(fields()[4].schema(), other.cvv);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing CardDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.CardDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bin)) {
        this.bin = data().deepCopy(fields()[0].schema(), other.bin);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cardHolderName)) {
        this.cardHolderName = data().deepCopy(fields()[1].schema(), other.cardHolderName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.expiryMonth)) {
        this.expiryMonth = data().deepCopy(fields()[2].schema(), other.expiryMonth);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.expiryYear)) {
        this.expiryYear = data().deepCopy(fields()[3].schema(), other.expiryYear);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cvv)) {
        this.cvv = data().deepCopy(fields()[4].schema(), other.cvv);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'bin' field.
      * @return The value.
      */
    public java.lang.CharSequence getBin() {
      return bin;
    }


    /**
      * Sets the value of the 'bin' field.
      * @param value The value of 'bin'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder setBin(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bin = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bin' field has been set.
      * @return True if the 'bin' field has been set, false otherwise.
      */
    public boolean hasBin() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bin' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder clearBin() {
      bin = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'cardHolderName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCardHolderName() {
      return cardHolderName;
    }


    /**
      * Sets the value of the 'cardHolderName' field.
      * @param value The value of 'cardHolderName'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder setCardHolderName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.cardHolderName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'cardHolderName' field has been set.
      * @return True if the 'cardHolderName' field has been set, false otherwise.
      */
    public boolean hasCardHolderName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'cardHolderName' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder clearCardHolderName() {
      cardHolderName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'expiryMonth' field.
      * @return The value.
      */
    public java.lang.CharSequence getExpiryMonth() {
      return expiryMonth;
    }


    /**
      * Sets the value of the 'expiryMonth' field.
      * @param value The value of 'expiryMonth'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder setExpiryMonth(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.expiryMonth = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'expiryMonth' field has been set.
      * @return True if the 'expiryMonth' field has been set, false otherwise.
      */
    public boolean hasExpiryMonth() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'expiryMonth' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder clearExpiryMonth() {
      expiryMonth = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'expiryYear' field.
      * @return The value.
      */
    public java.lang.CharSequence getExpiryYear() {
      return expiryYear;
    }


    /**
      * Sets the value of the 'expiryYear' field.
      * @param value The value of 'expiryYear'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder setExpiryYear(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.expiryYear = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'expiryYear' field has been set.
      * @return True if the 'expiryYear' field has been set, false otherwise.
      */
    public boolean hasExpiryYear() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'expiryYear' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder clearExpiryYear() {
      expiryYear = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'cvv' field.
      * @return The value.
      */
    public java.lang.CharSequence getCvv() {
      return cvv;
    }


    /**
      * Sets the value of the 'cvv' field.
      * @param value The value of 'cvv'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder setCvv(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.cvv = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'cvv' field has been set.
      * @return True if the 'cvv' field has been set, false otherwise.
      */
    public boolean hasCvv() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'cvv' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.CardDetails.Builder clearCvv() {
      cvv = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CardDetails build() {
      try {
        CardDetails record = new CardDetails();
        record.bin = fieldSetFlags()[0] ? this.bin : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.cardHolderName = fieldSetFlags()[1] ? this.cardHolderName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.expiryMonth = fieldSetFlags()[2] ? this.expiryMonth : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.expiryYear = fieldSetFlags()[3] ? this.expiryYear : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.cvv = fieldSetFlags()[4] ? this.cvv : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CardDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<CardDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CardDetails>
    READER$ = (org.apache.avro.io.DatumReader<CardDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.bin == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bin);
    }

    if (this.cardHolderName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.cardHolderName);
    }

    if (this.expiryMonth == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.expiryMonth);
    }

    if (this.expiryYear == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.expiryYear);
    }

    if (this.cvv == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.cvv);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.bin = null;
      } else {
        this.bin = in.readString(this.bin instanceof Utf8 ? (Utf8)this.bin : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.cardHolderName = null;
      } else {
        this.cardHolderName = in.readString(this.cardHolderName instanceof Utf8 ? (Utf8)this.cardHolderName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.expiryMonth = null;
      } else {
        this.expiryMonth = in.readString(this.expiryMonth instanceof Utf8 ? (Utf8)this.expiryMonth : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.expiryYear = null;
      } else {
        this.expiryYear = in.readString(this.expiryYear instanceof Utf8 ? (Utf8)this.expiryYear : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.cvv = null;
      } else {
        this.cvv = in.readString(this.cvv instanceof Utf8 ? (Utf8)this.cvv : null);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bin = null;
          } else {
            this.bin = in.readString(this.bin instanceof Utf8 ? (Utf8)this.bin : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.cardHolderName = null;
          } else {
            this.cardHolderName = in.readString(this.cardHolderName instanceof Utf8 ? (Utf8)this.cardHolderName : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.expiryMonth = null;
          } else {
            this.expiryMonth = in.readString(this.expiryMonth instanceof Utf8 ? (Utf8)this.expiryMonth : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.expiryYear = null;
          } else {
            this.expiryYear = in.readString(this.expiryYear instanceof Utf8 ? (Utf8)this.expiryYear : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.cvv = null;
          } else {
            this.cvv = in.readString(this.cvv instanceof Utf8 ? (Utf8)this.cvv : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (bin == null ? 0 : bin.hashCode());
    result = 31 * result + (cardHolderName == null ? 0 : cardHolderName.hashCode());
    result = 31 * result + (expiryMonth == null ? 0 : expiryMonth.hashCode());
    result = 31 * result + (expiryYear == null ? 0 : expiryYear.hashCode());
    result = 31 * result + (cvv == null ? 0 : cvv.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof CardDetails)) {
      return false;
    }
    CardDetails other = (CardDetails) o;
    if (Utf8.compareSequences(this.bin, other.bin) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.cardHolderName, other.cardHolderName) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.expiryMonth, other.expiryMonth) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.expiryYear, other.expiryYear) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.cvv, other.cvv) != 0) {
      return false;
    }
    return true;
  }
}










