/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaymentEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3846583639065281801L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentEvent\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"paymentId\",\"type\":\"string\",\"doc\":\"UUID-ul unic al tranzacției\"},{\"name\":\"amount\",\"type\":{\"type\":\"record\",\"name\":\"Amount\",\"fields\":[{\"name\":\"value\",\"type\":\"long\",\"doc\":\"Suma tranzacției exprimată în cea mai mică unitate monetară (de exemplu, bani pentru RON, cenți pentru EUR/USD)\"},{\"name\":\"currency\",\"type\":\"string\",\"doc\":\"Moneda (RON, EUR, USD)\"}]},\"doc\":\"Amount object with currency and value\"},{\"name\":\"cardDetails\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"CardDetails\",\"fields\":[{\"name\":\"cardNumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"cardHolderName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"expiryMonth\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"expiryYear\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"cvv\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"doc\":\"This will be removed in the future\"},{\"name\":\"tokenRef\",\"type\":[\"null\",\"string\"],\"doc\":\"This is the token for the card details\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Unix timestamp la momentul inițierii\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"symbols\":[\"PENDING\",\"VALIDATED\",\"REJECTED\",\"COMPLETED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** UUID-ul unic al tranzacției */
  private java.lang.CharSequence paymentId;
  /** Amount object with currency and value */
  private com.zaheudev.shared.avro.Amount amount;
  /** This will be removed in the future */
  private com.zaheudev.shared.avro.CardDetails cardDetails;
  /** This is the token for the card details */
  private java.lang.CharSequence tokenRef;
  /** Unix timestamp la momentul inițierii */
  private long timestamp;
  private com.zaheudev.shared.avro.PaymentStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentEvent() {}

  /**
   * All-args constructor.
   * @param paymentId UUID-ul unic al tranzacției
   * @param amount Amount object with currency and value
   * @param cardDetails This will be removed in the future
   * @param tokenRef This is the token for the card details
   * @param timestamp Unix timestamp la momentul inițierii
   * @param status The new value for status
   */
  public PaymentEvent(java.lang.CharSequence paymentId, com.zaheudev.shared.avro.Amount amount, com.zaheudev.shared.avro.CardDetails cardDetails, java.lang.CharSequence tokenRef, java.lang.Long timestamp, com.zaheudev.shared.avro.PaymentStatus status) {
    this.paymentId = paymentId;
    this.amount = amount;
    this.cardDetails = cardDetails;
    this.tokenRef = tokenRef;
    this.timestamp = timestamp;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return amount;
    case 2: return cardDetails;
    case 3: return tokenRef;
    case 4: return timestamp;
    case 5: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: amount = (com.zaheudev.shared.avro.Amount)value$; break;
    case 2: cardDetails = (com.zaheudev.shared.avro.CardDetails)value$; break;
    case 3: tokenRef = (java.lang.CharSequence)value$; break;
    case 4: timestamp = (java.lang.Long)value$; break;
    case 5: status = (com.zaheudev.shared.avro.PaymentStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return UUID-ul unic al tranzacției
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * UUID-ul unic al tranzacției
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return Amount object with currency and value
   */
  public com.zaheudev.shared.avro.Amount getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * Amount object with currency and value
   * @param value the value to set.
   */
  public void setAmount(com.zaheudev.shared.avro.Amount value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'cardDetails' field.
   * @return This will be removed in the future
   */
  public com.zaheudev.shared.avro.CardDetails getCardDetails() {
    return cardDetails;
  }


  /**
   * Sets the value of the 'cardDetails' field.
   * This will be removed in the future
   * @param value the value to set.
   */
  public void setCardDetails(com.zaheudev.shared.avro.CardDetails value) {
    this.cardDetails = value;
  }

  /**
   * Gets the value of the 'tokenRef' field.
   * @return This is the token for the card details
   */
  public java.lang.CharSequence getTokenRef() {
    return tokenRef;
  }


  /**
   * Sets the value of the 'tokenRef' field.
   * This is the token for the card details
   * @param value the value to set.
   */
  public void setTokenRef(java.lang.CharSequence value) {
    this.tokenRef = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Unix timestamp la momentul inițierii
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Unix timestamp la momentul inițierii
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.zaheudev.shared.avro.PaymentStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.zaheudev.shared.avro.PaymentStatus value) {
    this.status = value;
  }

  /**
   * Creates a new PaymentEvent RecordBuilder.
   * @return A new PaymentEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.PaymentEvent.Builder newBuilder() {
    return new com.zaheudev.shared.avro.PaymentEvent.Builder();
  }

  /**
   * Creates a new PaymentEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.PaymentEvent.Builder newBuilder(com.zaheudev.shared.avro.PaymentEvent.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.PaymentEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.PaymentEvent.Builder(other);
    }
  }

  /**
   * Creates a new PaymentEvent RecordBuilder by copying an existing PaymentEvent instance.
   * @param other The existing instance to copy.
   * @return A new PaymentEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.PaymentEvent.Builder newBuilder(com.zaheudev.shared.avro.PaymentEvent other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.PaymentEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.PaymentEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentEvent>
    implements org.apache.avro.data.RecordBuilder<PaymentEvent> {

    /** UUID-ul unic al tranzacției */
    private java.lang.CharSequence paymentId;
    /** Amount object with currency and value */
    private com.zaheudev.shared.avro.Amount amount;
    private com.zaheudev.shared.avro.Amount.Builder amountBuilder;
    /** This will be removed in the future */
    private com.zaheudev.shared.avro.CardDetails cardDetails;
    private com.zaheudev.shared.avro.CardDetails.Builder cardDetailsBuilder;
    /** This is the token for the card details */
    private java.lang.CharSequence tokenRef;
    /** Unix timestamp la momentul inițierii */
    private long timestamp;
    private com.zaheudev.shared.avro.PaymentStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.PaymentEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasAmountBuilder()) {
        this.amountBuilder = com.zaheudev.shared.avro.Amount.newBuilder(other.getAmountBuilder());
      }
      if (isValidValue(fields()[2], other.cardDetails)) {
        this.cardDetails = data().deepCopy(fields()[2].schema(), other.cardDetails);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasCardDetailsBuilder()) {
        this.cardDetailsBuilder = com.zaheudev.shared.avro.CardDetails.newBuilder(other.getCardDetailsBuilder());
      }
      if (isValidValue(fields()[3], other.tokenRef)) {
        this.tokenRef = data().deepCopy(fields()[3].schema(), other.tokenRef);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.PaymentEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = true;
      }
      this.amountBuilder = null;
      if (isValidValue(fields()[2], other.cardDetails)) {
        this.cardDetails = data().deepCopy(fields()[2].schema(), other.cardDetails);
        fieldSetFlags()[2] = true;
      }
      this.cardDetailsBuilder = null;
      if (isValidValue(fields()[3], other.tokenRef)) {
        this.tokenRef = data().deepCopy(fields()[3].schema(), other.tokenRef);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * UUID-ul unic al tranzacției
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * UUID-ul unic al tranzacției
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * UUID-ul unic al tranzacției
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * UUID-ul unic al tranzacției
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * Amount object with currency and value
      * @return The value.
      */
    public com.zaheudev.shared.avro.Amount getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * Amount object with currency and value
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder setAmount(com.zaheudev.shared.avro.Amount value) {
      validate(fields()[1], value);
      this.amountBuilder = null;
      this.amount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * Amount object with currency and value
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'amount' field and creates one if it doesn't exist yet.
     * Amount object with currency and value
     * @return This builder.
     */
    public com.zaheudev.shared.avro.Amount.Builder getAmountBuilder() {
      if (amountBuilder == null) {
        if (hasAmount()) {
          setAmountBuilder(com.zaheudev.shared.avro.Amount.newBuilder(amount));
        } else {
          setAmountBuilder(com.zaheudev.shared.avro.Amount.newBuilder());
        }
      }
      return amountBuilder;
    }

    /**
     * Sets the Builder instance for the 'amount' field
     * Amount object with currency and value
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.zaheudev.shared.avro.PaymentEvent.Builder setAmountBuilder(com.zaheudev.shared.avro.Amount.Builder value) {
      clearAmount();
      amountBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'amount' field has an active Builder instance
     * Amount object with currency and value
     * @return True if the 'amount' field has an active Builder instance
     */
    public boolean hasAmountBuilder() {
      return amountBuilder != null;
    }

    /**
      * Clears the value of the 'amount' field.
      * Amount object with currency and value
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder clearAmount() {
      amount = null;
      amountBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cardDetails' field.
      * This will be removed in the future
      * @return The value.
      */
    public com.zaheudev.shared.avro.CardDetails getCardDetails() {
      return cardDetails;
    }


    /**
      * Sets the value of the 'cardDetails' field.
      * This will be removed in the future
      * @param value The value of 'cardDetails'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder setCardDetails(com.zaheudev.shared.avro.CardDetails value) {
      validate(fields()[2], value);
      this.cardDetailsBuilder = null;
      this.cardDetails = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cardDetails' field has been set.
      * This will be removed in the future
      * @return True if the 'cardDetails' field has been set, false otherwise.
      */
    public boolean hasCardDetails() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'cardDetails' field and creates one if it doesn't exist yet.
     * This will be removed in the future
     * @return This builder.
     */
    public com.zaheudev.shared.avro.CardDetails.Builder getCardDetailsBuilder() {
      if (cardDetailsBuilder == null) {
        if (hasCardDetails()) {
          setCardDetailsBuilder(com.zaheudev.shared.avro.CardDetails.newBuilder(cardDetails));
        } else {
          setCardDetailsBuilder(com.zaheudev.shared.avro.CardDetails.newBuilder());
        }
      }
      return cardDetailsBuilder;
    }

    /**
     * Sets the Builder instance for the 'cardDetails' field
     * This will be removed in the future
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.zaheudev.shared.avro.PaymentEvent.Builder setCardDetailsBuilder(com.zaheudev.shared.avro.CardDetails.Builder value) {
      clearCardDetails();
      cardDetailsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'cardDetails' field has an active Builder instance
     * This will be removed in the future
     * @return True if the 'cardDetails' field has an active Builder instance
     */
    public boolean hasCardDetailsBuilder() {
      return cardDetailsBuilder != null;
    }

    /**
      * Clears the value of the 'cardDetails' field.
      * This will be removed in the future
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder clearCardDetails() {
      cardDetails = null;
      cardDetailsBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'tokenRef' field.
      * This is the token for the card details
      * @return The value.
      */
    public java.lang.CharSequence getTokenRef() {
      return tokenRef;
    }


    /**
      * Sets the value of the 'tokenRef' field.
      * This is the token for the card details
      * @param value The value of 'tokenRef'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder setTokenRef(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.tokenRef = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'tokenRef' field has been set.
      * This is the token for the card details
      * @return True if the 'tokenRef' field has been set, false otherwise.
      */
    public boolean hasTokenRef() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'tokenRef' field.
      * This is the token for the card details
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder clearTokenRef() {
      tokenRef = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Unix timestamp la momentul inițierii
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Unix timestamp la momentul inițierii
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Unix timestamp la momentul inițierii
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Unix timestamp la momentul inițierii
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.zaheudev.shared.avro.PaymentStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder setStatus(com.zaheudev.shared.avro.PaymentStatus value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentEvent build() {
      try {
        PaymentEvent record = new PaymentEvent();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (amountBuilder != null) {
          try {
            record.amount = this.amountBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("amount"));
            throw e;
          }
        } else {
          record.amount = fieldSetFlags()[1] ? this.amount : (com.zaheudev.shared.avro.Amount) defaultValue(fields()[1]);
        }
        if (cardDetailsBuilder != null) {
          try {
            record.cardDetails = this.cardDetailsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("cardDetails"));
            throw e;
          }
        } else {
          record.cardDetails = fieldSetFlags()[2] ? this.cardDetails : (com.zaheudev.shared.avro.CardDetails) defaultValue(fields()[2]);
        }
        record.tokenRef = fieldSetFlags()[3] ? this.tokenRef : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (com.zaheudev.shared.avro.PaymentStatus) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentEvent>
    READER$ = (org.apache.avro.io.DatumReader<PaymentEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentId);

    this.amount.customEncode(out);

    if (this.cardDetails == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.cardDetails.customEncode(out);
    }

    if (this.tokenRef == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.tokenRef);
    }

    out.writeLong(this.timestamp);

    out.writeEnum(this.status.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);

      if (this.amount == null) {
        this.amount = new com.zaheudev.shared.avro.Amount();
      }
      this.amount.customDecode(in);

      if (in.readIndex() != 1) {
        in.readNull();
        this.cardDetails = null;
      } else {
        if (this.cardDetails == null) {
          this.cardDetails = new com.zaheudev.shared.avro.CardDetails();
        }
        this.cardDetails.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.tokenRef = null;
      } else {
        this.tokenRef = in.readString(this.tokenRef instanceof Utf8 ? (Utf8)this.tokenRef : null);
      }

      this.timestamp = in.readLong();

      this.status = com.zaheudev.shared.avro.PaymentStatus.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          break;

        case 1:
          if (this.amount == null) {
            this.amount = new com.zaheudev.shared.avro.Amount();
          }
          this.amount.customDecode(in);
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.cardDetails = null;
          } else {
            if (this.cardDetails == null) {
              this.cardDetails = new com.zaheudev.shared.avro.CardDetails();
            }
            this.cardDetails.customDecode(in);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.tokenRef = null;
          } else {
            this.tokenRef = in.readString(this.tokenRef instanceof Utf8 ? (Utf8)this.tokenRef : null);
          }
          break;

        case 4:
          this.timestamp = in.readLong();
          break;

        case 5:
          this.status = com.zaheudev.shared.avro.PaymentStatus.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (amount == null ? 0 : amount.hashCode());
    result = 31 * result + (cardDetails == null ? 0 : cardDetails.hashCode());
    result = 31 * result + (tokenRef == null ? 0 : tokenRef.hashCode());
    result = 31 * result + Long.hashCode(timestamp);
    result = 31 * result + (status == null ? 0 : ((java.lang.Enum) status).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof PaymentEvent)) {
      return false;
    }
    PaymentEvent other = (PaymentEvent) o;
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.amount, other.amount)) {
      return false;
    }
    if (!java.util.Objects.equals(this.cardDetails, other.cardDetails)) {
      return false;
    }
    if (Utf8.compareSequences(this.tokenRef, other.tokenRef) != 0) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    if (!java.util.Objects.equals(this.status, other.status)) {
      return false;
    }
    return true;
  }
}










