/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaymentRequestedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4848581326124544038L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentRequestedEvent\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"paymentId\",\"type\":\"string\",\"doc\":\"UUID-ul unic al tranzacției\"},{\"name\":\"amount\",\"type\":{\"type\":\"record\",\"name\":\"Amount\",\"fields\":[{\"name\":\"value\",\"type\":\"long\",\"doc\":\"Suma tranzacției exprimată în cea mai mică unitate monetară (de exemplu, bani pentru RON, cenți pentru EUR/USD)\"},{\"name\":\"currency\",\"type\":\"string\",\"doc\":\"Moneda (RON, EUR, USD)\"}]},\"doc\":\"Amount object with currency and value\"},{\"name\":\"cardRecord\",\"type\":{\"type\":\"record\",\"name\":\"CardRecord\",\"fields\":[{\"name\":\"tokenRef\",\"type\":\"string\",\"doc\":\"This is the token for the card details\"},{\"name\":\"bin\",\"type\":\"string\",\"doc\":\"The first 6 digits of the card number\"},{\"name\":\"lastFour\",\"type\":\"string\"}]},\"doc\":\"This is the token for the card details\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Unix timestamp la momentul inițierii\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"symbols\":[\"PENDING\",\"VALIDATED\",\"REJECTED\",\"COMPLETED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentRequestedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentRequestedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentRequestedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentRequestedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentRequestedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentRequestedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentRequestedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentRequestedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentRequestedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** UUID-ul unic al tranzacției */
  private java.lang.CharSequence paymentId;
  /** Amount object with currency and value */
  private com.zaheudev.shared.avro.Amount amount;
  /** This is the token for the card details */
  private com.zaheudev.shared.avro.CardRecord cardRecord;
  /** Unix timestamp la momentul inițierii */
  private long timestamp;
  private com.zaheudev.shared.avro.PaymentStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentRequestedEvent() {}

  /**
   * All-args constructor.
   * @param paymentId UUID-ul unic al tranzacției
   * @param amount Amount object with currency and value
   * @param cardRecord This is the token for the card details
   * @param timestamp Unix timestamp la momentul inițierii
   * @param status The new value for status
   */
  public PaymentRequestedEvent(java.lang.CharSequence paymentId, com.zaheudev.shared.avro.Amount amount, com.zaheudev.shared.avro.CardRecord cardRecord, java.lang.Long timestamp, com.zaheudev.shared.avro.PaymentStatus status) {
    this.paymentId = paymentId;
    this.amount = amount;
    this.cardRecord = cardRecord;
    this.timestamp = timestamp;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return amount;
    case 2: return cardRecord;
    case 3: return timestamp;
    case 4: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: amount = (com.zaheudev.shared.avro.Amount)value$; break;
    case 2: cardRecord = (com.zaheudev.shared.avro.CardRecord)value$; break;
    case 3: timestamp = (java.lang.Long)value$; break;
    case 4: status = (com.zaheudev.shared.avro.PaymentStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return UUID-ul unic al tranzacției
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * UUID-ul unic al tranzacției
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return Amount object with currency and value
   */
  public com.zaheudev.shared.avro.Amount getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * Amount object with currency and value
   * @param value the value to set.
   */
  public void setAmount(com.zaheudev.shared.avro.Amount value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'cardRecord' field.
   * @return This is the token for the card details
   */
  public com.zaheudev.shared.avro.CardRecord getCardRecord() {
    return cardRecord;
  }


  /**
   * Sets the value of the 'cardRecord' field.
   * This is the token for the card details
   * @param value the value to set.
   */
  public void setCardRecord(com.zaheudev.shared.avro.CardRecord value) {
    this.cardRecord = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Unix timestamp la momentul inițierii
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Unix timestamp la momentul inițierii
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.zaheudev.shared.avro.PaymentStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.zaheudev.shared.avro.PaymentStatus value) {
    this.status = value;
  }

  /**
   * Creates a new PaymentRequestedEvent RecordBuilder.
   * @return A new PaymentRequestedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.PaymentRequestedEvent.Builder newBuilder() {
    return new com.zaheudev.shared.avro.PaymentRequestedEvent.Builder();
  }

  /**
   * Creates a new PaymentRequestedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentRequestedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.PaymentRequestedEvent.Builder newBuilder(com.zaheudev.shared.avro.PaymentRequestedEvent.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.PaymentRequestedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.PaymentRequestedEvent.Builder(other);
    }
  }

  /**
   * Creates a new PaymentRequestedEvent RecordBuilder by copying an existing PaymentRequestedEvent instance.
   * @param other The existing instance to copy.
   * @return A new PaymentRequestedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.PaymentRequestedEvent.Builder newBuilder(com.zaheudev.shared.avro.PaymentRequestedEvent other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.PaymentRequestedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.PaymentRequestedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentRequestedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentRequestedEvent>
    implements org.apache.avro.data.RecordBuilder<PaymentRequestedEvent> {

    /** UUID-ul unic al tranzacției */
    private java.lang.CharSequence paymentId;
    /** Amount object with currency and value */
    private com.zaheudev.shared.avro.Amount amount;
    private com.zaheudev.shared.avro.Amount.Builder amountBuilder;
    /** This is the token for the card details */
    private com.zaheudev.shared.avro.CardRecord cardRecord;
    private com.zaheudev.shared.avro.CardRecord.Builder cardRecordBuilder;
    /** Unix timestamp la momentul inițierii */
    private long timestamp;
    private com.zaheudev.shared.avro.PaymentStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.PaymentRequestedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasAmountBuilder()) {
        this.amountBuilder = com.zaheudev.shared.avro.Amount.newBuilder(other.getAmountBuilder());
      }
      if (isValidValue(fields()[2], other.cardRecord)) {
        this.cardRecord = data().deepCopy(fields()[2].schema(), other.cardRecord);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasCardRecordBuilder()) {
        this.cardRecordBuilder = com.zaheudev.shared.avro.CardRecord.newBuilder(other.getCardRecordBuilder());
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentRequestedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.PaymentRequestedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = true;
      }
      this.amountBuilder = null;
      if (isValidValue(fields()[2], other.cardRecord)) {
        this.cardRecord = data().deepCopy(fields()[2].schema(), other.cardRecord);
        fieldSetFlags()[2] = true;
      }
      this.cardRecordBuilder = null;
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * UUID-ul unic al tranzacției
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * UUID-ul unic al tranzacției
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * UUID-ul unic al tranzacției
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * UUID-ul unic al tranzacției
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * Amount object with currency and value
      * @return The value.
      */
    public com.zaheudev.shared.avro.Amount getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * Amount object with currency and value
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder setAmount(com.zaheudev.shared.avro.Amount value) {
      validate(fields()[1], value);
      this.amountBuilder = null;
      this.amount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * Amount object with currency and value
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'amount' field and creates one if it doesn't exist yet.
     * Amount object with currency and value
     * @return This builder.
     */
    public com.zaheudev.shared.avro.Amount.Builder getAmountBuilder() {
      if (amountBuilder == null) {
        if (hasAmount()) {
          setAmountBuilder(com.zaheudev.shared.avro.Amount.newBuilder(amount));
        } else {
          setAmountBuilder(com.zaheudev.shared.avro.Amount.newBuilder());
        }
      }
      return amountBuilder;
    }

    /**
     * Sets the Builder instance for the 'amount' field
     * Amount object with currency and value
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder setAmountBuilder(com.zaheudev.shared.avro.Amount.Builder value) {
      clearAmount();
      amountBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'amount' field has an active Builder instance
     * Amount object with currency and value
     * @return True if the 'amount' field has an active Builder instance
     */
    public boolean hasAmountBuilder() {
      return amountBuilder != null;
    }

    /**
      * Clears the value of the 'amount' field.
      * Amount object with currency and value
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder clearAmount() {
      amount = null;
      amountBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cardRecord' field.
      * This is the token for the card details
      * @return The value.
      */
    public com.zaheudev.shared.avro.CardRecord getCardRecord() {
      return cardRecord;
    }


    /**
      * Sets the value of the 'cardRecord' field.
      * This is the token for the card details
      * @param value The value of 'cardRecord'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder setCardRecord(com.zaheudev.shared.avro.CardRecord value) {
      validate(fields()[2], value);
      this.cardRecordBuilder = null;
      this.cardRecord = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cardRecord' field has been set.
      * This is the token for the card details
      * @return True if the 'cardRecord' field has been set, false otherwise.
      */
    public boolean hasCardRecord() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'cardRecord' field and creates one if it doesn't exist yet.
     * This is the token for the card details
     * @return This builder.
     */
    public com.zaheudev.shared.avro.CardRecord.Builder getCardRecordBuilder() {
      if (cardRecordBuilder == null) {
        if (hasCardRecord()) {
          setCardRecordBuilder(com.zaheudev.shared.avro.CardRecord.newBuilder(cardRecord));
        } else {
          setCardRecordBuilder(com.zaheudev.shared.avro.CardRecord.newBuilder());
        }
      }
      return cardRecordBuilder;
    }

    /**
     * Sets the Builder instance for the 'cardRecord' field
     * This is the token for the card details
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder setCardRecordBuilder(com.zaheudev.shared.avro.CardRecord.Builder value) {
      clearCardRecord();
      cardRecordBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'cardRecord' field has an active Builder instance
     * This is the token for the card details
     * @return True if the 'cardRecord' field has an active Builder instance
     */
    public boolean hasCardRecordBuilder() {
      return cardRecordBuilder != null;
    }

    /**
      * Clears the value of the 'cardRecord' field.
      * This is the token for the card details
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder clearCardRecord() {
      cardRecord = null;
      cardRecordBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Unix timestamp la momentul inițierii
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Unix timestamp la momentul inițierii
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder setTimestamp(long value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Unix timestamp la momentul inițierii
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Unix timestamp la momentul inițierii
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.zaheudev.shared.avro.PaymentStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder setStatus(com.zaheudev.shared.avro.PaymentStatus value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.PaymentRequestedEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentRequestedEvent build() {
      try {
        PaymentRequestedEvent record = new PaymentRequestedEvent();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (amountBuilder != null) {
          try {
            record.amount = this.amountBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("amount"));
            throw e;
          }
        } else {
          record.amount = fieldSetFlags()[1] ? this.amount : (com.zaheudev.shared.avro.Amount) defaultValue(fields()[1]);
        }
        if (cardRecordBuilder != null) {
          try {
            record.cardRecord = this.cardRecordBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("cardRecord"));
            throw e;
          }
        } else {
          record.cardRecord = fieldSetFlags()[2] ? this.cardRecord : (com.zaheudev.shared.avro.CardRecord) defaultValue(fields()[2]);
        }
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.Long) defaultValue(fields()[3]);
        record.status = fieldSetFlags()[4] ? this.status : (com.zaheudev.shared.avro.PaymentStatus) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentRequestedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentRequestedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentRequestedEvent>
    READER$ = (org.apache.avro.io.DatumReader<PaymentRequestedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentId);

    this.amount.customEncode(out);

    this.cardRecord.customEncode(out);

    out.writeLong(this.timestamp);

    out.writeEnum(this.status.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);

      if (this.amount == null) {
        this.amount = new com.zaheudev.shared.avro.Amount();
      }
      this.amount.customDecode(in);

      if (this.cardRecord == null) {
        this.cardRecord = new com.zaheudev.shared.avro.CardRecord();
      }
      this.cardRecord.customDecode(in);

      this.timestamp = in.readLong();

      this.status = com.zaheudev.shared.avro.PaymentStatus.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          break;

        case 1:
          if (this.amount == null) {
            this.amount = new com.zaheudev.shared.avro.Amount();
          }
          this.amount.customDecode(in);
          break;

        case 2:
          if (this.cardRecord == null) {
            this.cardRecord = new com.zaheudev.shared.avro.CardRecord();
          }
          this.cardRecord.customDecode(in);
          break;

        case 3:
          this.timestamp = in.readLong();
          break;

        case 4:
          this.status = com.zaheudev.shared.avro.PaymentStatus.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (amount == null ? 0 : amount.hashCode());
    result = 31 * result + (cardRecord == null ? 0 : cardRecord.hashCode());
    result = 31 * result + Long.hashCode(timestamp);
    result = 31 * result + (status == null ? 0 : ((java.lang.Enum) status).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof PaymentRequestedEvent)) {
      return false;
    }
    PaymentRequestedEvent other = (PaymentRequestedEvent) o;
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.amount, other.amount)) {
      return false;
    }
    if (!java.util.Objects.equals(this.cardRecord, other.cardRecord)) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    if (!java.util.Objects.equals(this.status, other.status)) {
      return false;
    }
    return true;
  }
}










