/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentMethodEnum implements org.apache.avro.generic.GenericEnumSymbol<PaymentMethodEnum> {
  VISA, MASTERCARD, AMEX, DISCOVER, ACCEL, STAR, NYCE, PULSE, MAESTRO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentMethodEnum\",\"namespace\":\"com.zaheudev.shared.avro\",\"symbols\":[\"VISA\",\"MASTERCARD\",\"AMEX\",\"DISCOVER\",\"ACCEL\",\"STAR\",\"NYCE\",\"PULSE\",\"MAESTRO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
