/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RefundCompletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1550025503273265066L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RefundCompletedEvent\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"success\",\"type\":[\"null\",\"boolean\"],\"default\":false},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"paymentId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"originalProcessorTransactionId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"errorMessage\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"refundRrn\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"refundAuthCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"refundId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"refundedAmount\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Amount\",\"fields\":[{\"name\":\"value\",\"type\":\"long\",\"doc\":\"Suma tranzacției exprimată în cea mai mică unitate monetară (de exemplu, bani pentru RON, cenți pentru EUR/USD)\"},{\"name\":\"currency\",\"type\":\"string\",\"doc\":\"Moneda (RON, EUR, USD)\"}]}],\"default\":null},{\"name\":\"currency\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"createdAt\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"updatedAt\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"timeStamp\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RefundCompletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RefundCompletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RefundCompletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RefundCompletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RefundCompletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RefundCompletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RefundCompletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RefundCompletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RefundCompletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Boolean success;
  private java.lang.CharSequence status;
  private java.lang.CharSequence paymentId;
  private java.lang.CharSequence originalProcessorTransactionId;
  private java.lang.CharSequence errorMessage;
  private java.lang.CharSequence refundRrn;
  private java.lang.CharSequence refundAuthCode;
  private java.lang.CharSequence refundId;
  private com.zaheudev.shared.avro.Amount refundedAmount;
  private java.lang.CharSequence currency;
  private java.lang.CharSequence createdAt;
  private java.lang.CharSequence updatedAt;
  private java.lang.Long timeStamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RefundCompletedEvent() {}

  /**
   * All-args constructor.
   * @param success The new value for success
   * @param status The new value for status
   * @param paymentId The new value for paymentId
   * @param originalProcessorTransactionId The new value for originalProcessorTransactionId
   * @param errorMessage The new value for errorMessage
   * @param refundRrn The new value for refundRrn
   * @param refundAuthCode The new value for refundAuthCode
   * @param refundId The new value for refundId
   * @param refundedAmount The new value for refundedAmount
   * @param currency The new value for currency
   * @param createdAt The new value for createdAt
   * @param updatedAt The new value for updatedAt
   * @param timeStamp The new value for timeStamp
   */
  public RefundCompletedEvent(java.lang.Boolean success, java.lang.CharSequence status, java.lang.CharSequence paymentId, java.lang.CharSequence originalProcessorTransactionId, java.lang.CharSequence errorMessage, java.lang.CharSequence refundRrn, java.lang.CharSequence refundAuthCode, java.lang.CharSequence refundId, com.zaheudev.shared.avro.Amount refundedAmount, java.lang.CharSequence currency, java.lang.CharSequence createdAt, java.lang.CharSequence updatedAt, java.lang.Long timeStamp) {
    this.success = success;
    this.status = status;
    this.paymentId = paymentId;
    this.originalProcessorTransactionId = originalProcessorTransactionId;
    this.errorMessage = errorMessage;
    this.refundRrn = refundRrn;
    this.refundAuthCode = refundAuthCode;
    this.refundId = refundId;
    this.refundedAmount = refundedAmount;
    this.currency = currency;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.timeStamp = timeStamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return success;
    case 1: return status;
    case 2: return paymentId;
    case 3: return originalProcessorTransactionId;
    case 4: return errorMessage;
    case 5: return refundRrn;
    case 6: return refundAuthCode;
    case 7: return refundId;
    case 8: return refundedAmount;
    case 9: return currency;
    case 10: return createdAt;
    case 11: return updatedAt;
    case 12: return timeStamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: success = (java.lang.Boolean)value$; break;
    case 1: status = (java.lang.CharSequence)value$; break;
    case 2: paymentId = (java.lang.CharSequence)value$; break;
    case 3: originalProcessorTransactionId = (java.lang.CharSequence)value$; break;
    case 4: errorMessage = (java.lang.CharSequence)value$; break;
    case 5: refundRrn = (java.lang.CharSequence)value$; break;
    case 6: refundAuthCode = (java.lang.CharSequence)value$; break;
    case 7: refundId = (java.lang.CharSequence)value$; break;
    case 8: refundedAmount = (com.zaheudev.shared.avro.Amount)value$; break;
    case 9: currency = (java.lang.CharSequence)value$; break;
    case 10: createdAt = (java.lang.CharSequence)value$; break;
    case 11: updatedAt = (java.lang.CharSequence)value$; break;
    case 12: timeStamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'success' field.
   * @return The value of the 'success' field.
   */
  public java.lang.Boolean getSuccess() {
    return success;
  }


  /**
   * Sets the value of the 'success' field.
   * @param value the value to set.
   */
  public void setSuccess(java.lang.Boolean value) {
    this.success = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'originalProcessorTransactionId' field.
   * @return The value of the 'originalProcessorTransactionId' field.
   */
  public java.lang.CharSequence getOriginalProcessorTransactionId() {
    return originalProcessorTransactionId;
  }


  /**
   * Sets the value of the 'originalProcessorTransactionId' field.
   * @param value the value to set.
   */
  public void setOriginalProcessorTransactionId(java.lang.CharSequence value) {
    this.originalProcessorTransactionId = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.CharSequence getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.CharSequence value) {
    this.errorMessage = value;
  }

  /**
   * Gets the value of the 'refundRrn' field.
   * @return The value of the 'refundRrn' field.
   */
  public java.lang.CharSequence getRefundRrn() {
    return refundRrn;
  }


  /**
   * Sets the value of the 'refundRrn' field.
   * @param value the value to set.
   */
  public void setRefundRrn(java.lang.CharSequence value) {
    this.refundRrn = value;
  }

  /**
   * Gets the value of the 'refundAuthCode' field.
   * @return The value of the 'refundAuthCode' field.
   */
  public java.lang.CharSequence getRefundAuthCode() {
    return refundAuthCode;
  }


  /**
   * Sets the value of the 'refundAuthCode' field.
   * @param value the value to set.
   */
  public void setRefundAuthCode(java.lang.CharSequence value) {
    this.refundAuthCode = value;
  }

  /**
   * Gets the value of the 'refundId' field.
   * @return The value of the 'refundId' field.
   */
  public java.lang.CharSequence getRefundId() {
    return refundId;
  }


  /**
   * Sets the value of the 'refundId' field.
   * @param value the value to set.
   */
  public void setRefundId(java.lang.CharSequence value) {
    this.refundId = value;
  }

  /**
   * Gets the value of the 'refundedAmount' field.
   * @return The value of the 'refundedAmount' field.
   */
  public com.zaheudev.shared.avro.Amount getRefundedAmount() {
    return refundedAmount;
  }


  /**
   * Sets the value of the 'refundedAmount' field.
   * @param value the value to set.
   */
  public void setRefundedAmount(com.zaheudev.shared.avro.Amount value) {
    this.refundedAmount = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.lang.CharSequence getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.CharSequence value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'updatedAt' field.
   * @return The value of the 'updatedAt' field.
   */
  public java.lang.CharSequence getUpdatedAt() {
    return updatedAt;
  }


  /**
   * Sets the value of the 'updatedAt' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.CharSequence value) {
    this.updatedAt = value;
  }

  /**
   * Gets the value of the 'timeStamp' field.
   * @return The value of the 'timeStamp' field.
   */
  public java.lang.Long getTimeStamp() {
    return timeStamp;
  }


  /**
   * Sets the value of the 'timeStamp' field.
   * @param value the value to set.
   */
  public void setTimeStamp(java.lang.Long value) {
    this.timeStamp = value;
  }

  /**
   * Creates a new RefundCompletedEvent RecordBuilder.
   * @return A new RefundCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RefundCompletedEvent.Builder newBuilder() {
    return new com.zaheudev.shared.avro.RefundCompletedEvent.Builder();
  }

  /**
   * Creates a new RefundCompletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RefundCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RefundCompletedEvent.Builder newBuilder(com.zaheudev.shared.avro.RefundCompletedEvent.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RefundCompletedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.RefundCompletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new RefundCompletedEvent RecordBuilder by copying an existing RefundCompletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new RefundCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RefundCompletedEvent.Builder newBuilder(com.zaheudev.shared.avro.RefundCompletedEvent other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RefundCompletedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.RefundCompletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RefundCompletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RefundCompletedEvent>
    implements org.apache.avro.data.RecordBuilder<RefundCompletedEvent> {

    private java.lang.Boolean success;
    private java.lang.CharSequence status;
    private java.lang.CharSequence paymentId;
    private java.lang.CharSequence originalProcessorTransactionId;
    private java.lang.CharSequence errorMessage;
    private java.lang.CharSequence refundRrn;
    private java.lang.CharSequence refundAuthCode;
    private java.lang.CharSequence refundId;
    private com.zaheudev.shared.avro.Amount refundedAmount;
    private com.zaheudev.shared.avro.Amount.Builder refundedAmountBuilder;
    private java.lang.CharSequence currency;
    private java.lang.CharSequence createdAt;
    private java.lang.CharSequence updatedAt;
    private java.lang.Long timeStamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.RefundCompletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.success)) {
        this.success = data().deepCopy(fields()[0].schema(), other.success);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[2].schema(), other.paymentId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.originalProcessorTransactionId)) {
        this.originalProcessorTransactionId = data().deepCopy(fields()[3].schema(), other.originalProcessorTransactionId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[4].schema(), other.errorMessage);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.refundRrn)) {
        this.refundRrn = data().deepCopy(fields()[5].schema(), other.refundRrn);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.refundAuthCode)) {
        this.refundAuthCode = data().deepCopy(fields()[6].schema(), other.refundAuthCode);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.refundId)) {
        this.refundId = data().deepCopy(fields()[7].schema(), other.refundId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.refundedAmount)) {
        this.refundedAmount = data().deepCopy(fields()[8].schema(), other.refundedAmount);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (other.hasRefundedAmountBuilder()) {
        this.refundedAmountBuilder = com.zaheudev.shared.avro.Amount.newBuilder(other.getRefundedAmountBuilder());
      }
      if (isValidValue(fields()[9], other.currency)) {
        this.currency = data().deepCopy(fields()[9].schema(), other.currency);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[10].schema(), other.createdAt);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[11].schema(), other.updatedAt);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.timeStamp)) {
        this.timeStamp = data().deepCopy(fields()[12].schema(), other.timeStamp);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
    }

    /**
     * Creates a Builder by copying an existing RefundCompletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.RefundCompletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.success)) {
        this.success = data().deepCopy(fields()[0].schema(), other.success);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[2].schema(), other.paymentId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.originalProcessorTransactionId)) {
        this.originalProcessorTransactionId = data().deepCopy(fields()[3].schema(), other.originalProcessorTransactionId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[4].schema(), other.errorMessage);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.refundRrn)) {
        this.refundRrn = data().deepCopy(fields()[5].schema(), other.refundRrn);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.refundAuthCode)) {
        this.refundAuthCode = data().deepCopy(fields()[6].schema(), other.refundAuthCode);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.refundId)) {
        this.refundId = data().deepCopy(fields()[7].schema(), other.refundId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.refundedAmount)) {
        this.refundedAmount = data().deepCopy(fields()[8].schema(), other.refundedAmount);
        fieldSetFlags()[8] = true;
      }
      this.refundedAmountBuilder = null;
      if (isValidValue(fields()[9], other.currency)) {
        this.currency = data().deepCopy(fields()[9].schema(), other.currency);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[10].schema(), other.createdAt);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[11].schema(), other.updatedAt);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.timeStamp)) {
        this.timeStamp = data().deepCopy(fields()[12].schema(), other.timeStamp);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'success' field.
      * @return The value.
      */
    public java.lang.Boolean getSuccess() {
      return success;
    }


    /**
      * Sets the value of the 'success' field.
      * @param value The value of 'success'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setSuccess(java.lang.Boolean value) {
      validate(fields()[0], value);
      this.success = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'success' field has been set.
      * @return True if the 'success' field has been set, false otherwise.
      */
    public boolean hasSuccess() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'success' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearSuccess() {
      success = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.paymentId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'originalProcessorTransactionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOriginalProcessorTransactionId() {
      return originalProcessorTransactionId;
    }


    /**
      * Sets the value of the 'originalProcessorTransactionId' field.
      * @param value The value of 'originalProcessorTransactionId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setOriginalProcessorTransactionId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.originalProcessorTransactionId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'originalProcessorTransactionId' field has been set.
      * @return True if the 'originalProcessorTransactionId' field has been set, false otherwise.
      */
    public boolean hasOriginalProcessorTransactionId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'originalProcessorTransactionId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearOriginalProcessorTransactionId() {
      originalProcessorTransactionId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.CharSequence getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setErrorMessage(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.errorMessage = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'refundRrn' field.
      * @return The value.
      */
    public java.lang.CharSequence getRefundRrn() {
      return refundRrn;
    }


    /**
      * Sets the value of the 'refundRrn' field.
      * @param value The value of 'refundRrn'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setRefundRrn(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.refundRrn = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'refundRrn' field has been set.
      * @return True if the 'refundRrn' field has been set, false otherwise.
      */
    public boolean hasRefundRrn() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'refundRrn' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearRefundRrn() {
      refundRrn = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'refundAuthCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getRefundAuthCode() {
      return refundAuthCode;
    }


    /**
      * Sets the value of the 'refundAuthCode' field.
      * @param value The value of 'refundAuthCode'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setRefundAuthCode(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.refundAuthCode = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'refundAuthCode' field has been set.
      * @return True if the 'refundAuthCode' field has been set, false otherwise.
      */
    public boolean hasRefundAuthCode() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'refundAuthCode' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearRefundAuthCode() {
      refundAuthCode = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'refundId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRefundId() {
      return refundId;
    }


    /**
      * Sets the value of the 'refundId' field.
      * @param value The value of 'refundId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setRefundId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.refundId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'refundId' field has been set.
      * @return True if the 'refundId' field has been set, false otherwise.
      */
    public boolean hasRefundId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'refundId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearRefundId() {
      refundId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'refundedAmount' field.
      * @return The value.
      */
    public com.zaheudev.shared.avro.Amount getRefundedAmount() {
      return refundedAmount;
    }


    /**
      * Sets the value of the 'refundedAmount' field.
      * @param value The value of 'refundedAmount'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setRefundedAmount(com.zaheudev.shared.avro.Amount value) {
      validate(fields()[8], value);
      this.refundedAmountBuilder = null;
      this.refundedAmount = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'refundedAmount' field has been set.
      * @return True if the 'refundedAmount' field has been set, false otherwise.
      */
    public boolean hasRefundedAmount() {
      return fieldSetFlags()[8];
    }

    /**
     * Gets the Builder instance for the 'refundedAmount' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.zaheudev.shared.avro.Amount.Builder getRefundedAmountBuilder() {
      if (refundedAmountBuilder == null) {
        if (hasRefundedAmount()) {
          setRefundedAmountBuilder(com.zaheudev.shared.avro.Amount.newBuilder(refundedAmount));
        } else {
          setRefundedAmountBuilder(com.zaheudev.shared.avro.Amount.newBuilder());
        }
      }
      return refundedAmountBuilder;
    }

    /**
     * Sets the Builder instance for the 'refundedAmount' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setRefundedAmountBuilder(com.zaheudev.shared.avro.Amount.Builder value) {
      clearRefundedAmount();
      refundedAmountBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'refundedAmount' field has an active Builder instance
     * @return True if the 'refundedAmount' field has an active Builder instance
     */
    public boolean hasRefundedAmountBuilder() {
      return refundedAmountBuilder != null;
    }

    /**
      * Clears the value of the 'refundedAmount' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearRefundedAmount() {
      refundedAmount = null;
      refundedAmountBuilder = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.currency = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setCreatedAt(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.createdAt = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setUpdatedAt(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.updatedAt = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearUpdatedAt() {
      updatedAt = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeStamp' field.
      * @return The value.
      */
    public java.lang.Long getTimeStamp() {
      return timeStamp;
    }


    /**
      * Sets the value of the 'timeStamp' field.
      * @param value The value of 'timeStamp'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder setTimeStamp(java.lang.Long value) {
      validate(fields()[12], value);
      this.timeStamp = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'timeStamp' field has been set.
      * @return True if the 'timeStamp' field has been set, false otherwise.
      */
    public boolean hasTimeStamp() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'timeStamp' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundCompletedEvent.Builder clearTimeStamp() {
      timeStamp = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RefundCompletedEvent build() {
      try {
        RefundCompletedEvent record = new RefundCompletedEvent();
        record.success = fieldSetFlags()[0] ? this.success : (java.lang.Boolean) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.paymentId = fieldSetFlags()[2] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.originalProcessorTransactionId = fieldSetFlags()[3] ? this.originalProcessorTransactionId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.errorMessage = fieldSetFlags()[4] ? this.errorMessage : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.refundRrn = fieldSetFlags()[5] ? this.refundRrn : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.refundAuthCode = fieldSetFlags()[6] ? this.refundAuthCode : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.refundId = fieldSetFlags()[7] ? this.refundId : (java.lang.CharSequence) defaultValue(fields()[7]);
        if (refundedAmountBuilder != null) {
          try {
            record.refundedAmount = this.refundedAmountBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("refundedAmount"));
            throw e;
          }
        } else {
          record.refundedAmount = fieldSetFlags()[8] ? this.refundedAmount : (com.zaheudev.shared.avro.Amount) defaultValue(fields()[8]);
        }
        record.currency = fieldSetFlags()[9] ? this.currency : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.createdAt = fieldSetFlags()[10] ? this.createdAt : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.updatedAt = fieldSetFlags()[11] ? this.updatedAt : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.timeStamp = fieldSetFlags()[12] ? this.timeStamp : (java.lang.Long) defaultValue(fields()[12]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RefundCompletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RefundCompletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RefundCompletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<RefundCompletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.success == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.success);
    }

    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status);
    }

    if (this.paymentId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.paymentId);
    }

    if (this.originalProcessorTransactionId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.originalProcessorTransactionId);
    }

    if (this.errorMessage == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.errorMessage);
    }

    if (this.refundRrn == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.refundRrn);
    }

    if (this.refundAuthCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.refundAuthCode);
    }

    if (this.refundId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.refundId);
    }

    if (this.refundedAmount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.refundedAmount.customEncode(out);
    }

    if (this.currency == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.currency);
    }

    if (this.createdAt == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.createdAt);
    }

    if (this.updatedAt == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.updatedAt);
    }

    if (this.timeStamp == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.timeStamp);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.success = null;
      } else {
        this.success = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.paymentId = null;
      } else {
        this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.originalProcessorTransactionId = null;
      } else {
        this.originalProcessorTransactionId = in.readString(this.originalProcessorTransactionId instanceof Utf8 ? (Utf8)this.originalProcessorTransactionId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.errorMessage = null;
      } else {
        this.errorMessage = in.readString(this.errorMessage instanceof Utf8 ? (Utf8)this.errorMessage : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.refundRrn = null;
      } else {
        this.refundRrn = in.readString(this.refundRrn instanceof Utf8 ? (Utf8)this.refundRrn : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.refundAuthCode = null;
      } else {
        this.refundAuthCode = in.readString(this.refundAuthCode instanceof Utf8 ? (Utf8)this.refundAuthCode : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.refundId = null;
      } else {
        this.refundId = in.readString(this.refundId instanceof Utf8 ? (Utf8)this.refundId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.refundedAmount = null;
      } else {
        if (this.refundedAmount == null) {
          this.refundedAmount = new com.zaheudev.shared.avro.Amount();
        }
        this.refundedAmount.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.currency = null;
      } else {
        this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.createdAt = null;
      } else {
        this.createdAt = in.readString(this.createdAt instanceof Utf8 ? (Utf8)this.createdAt : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.updatedAt = null;
      } else {
        this.updatedAt = in.readString(this.updatedAt instanceof Utf8 ? (Utf8)this.updatedAt : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.timeStamp = null;
      } else {
        this.timeStamp = in.readLong();
      }

    } else {
      for (int i = 0; i < 13; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.success = null;
          } else {
            this.success = in.readBoolean();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.paymentId = null;
          } else {
            this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.originalProcessorTransactionId = null;
          } else {
            this.originalProcessorTransactionId = in.readString(this.originalProcessorTransactionId instanceof Utf8 ? (Utf8)this.originalProcessorTransactionId : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.errorMessage = null;
          } else {
            this.errorMessage = in.readString(this.errorMessage instanceof Utf8 ? (Utf8)this.errorMessage : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.refundRrn = null;
          } else {
            this.refundRrn = in.readString(this.refundRrn instanceof Utf8 ? (Utf8)this.refundRrn : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.refundAuthCode = null;
          } else {
            this.refundAuthCode = in.readString(this.refundAuthCode instanceof Utf8 ? (Utf8)this.refundAuthCode : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.refundId = null;
          } else {
            this.refundId = in.readString(this.refundId instanceof Utf8 ? (Utf8)this.refundId : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.refundedAmount = null;
          } else {
            if (this.refundedAmount == null) {
              this.refundedAmount = new com.zaheudev.shared.avro.Amount();
            }
            this.refundedAmount.customDecode(in);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.currency = null;
          } else {
            this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.createdAt = null;
          } else {
            this.createdAt = in.readString(this.createdAt instanceof Utf8 ? (Utf8)this.createdAt : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.updatedAt = null;
          } else {
            this.updatedAt = in.readString(this.updatedAt instanceof Utf8 ? (Utf8)this.updatedAt : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.timeStamp = null;
          } else {
            this.timeStamp = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (success == null ? 0 : success.hashCode());
    result = 31 * result + (status == null ? 0 : status.hashCode());
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (originalProcessorTransactionId == null ? 0 : originalProcessorTransactionId.hashCode());
    result = 31 * result + (errorMessage == null ? 0 : errorMessage.hashCode());
    result = 31 * result + (refundRrn == null ? 0 : refundRrn.hashCode());
    result = 31 * result + (refundAuthCode == null ? 0 : refundAuthCode.hashCode());
    result = 31 * result + (refundId == null ? 0 : refundId.hashCode());
    result = 31 * result + (refundedAmount == null ? 0 : refundedAmount.hashCode());
    result = 31 * result + (currency == null ? 0 : currency.hashCode());
    result = 31 * result + (createdAt == null ? 0 : createdAt.hashCode());
    result = 31 * result + (updatedAt == null ? 0 : updatedAt.hashCode());
    result = 31 * result + (timeStamp == null ? 0 : timeStamp.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof RefundCompletedEvent)) {
      return false;
    }
    RefundCompletedEvent other = (RefundCompletedEvent) o;
    if (!java.util.Objects.equals(this.success, other.success)) {
      return false;
    }
    if (Utf8.compareSequences(this.status, other.status) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.originalProcessorTransactionId, other.originalProcessorTransactionId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.errorMessage, other.errorMessage) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.refundRrn, other.refundRrn) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.refundAuthCode, other.refundAuthCode) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.refundId, other.refundId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.refundedAmount, other.refundedAmount)) {
      return false;
    }
    if (Utf8.compareSequences(this.currency, other.currency) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.createdAt, other.createdAt) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.updatedAt, other.updatedAt) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.timeStamp, other.timeStamp)) {
      return false;
    }
    return true;
  }
}










