/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RefundRequestedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7554699869803597378L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RefundRequestedEvent\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"paymentId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"refundAmount\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RefundRequestedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RefundRequestedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RefundRequestedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RefundRequestedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RefundRequestedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RefundRequestedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RefundRequestedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RefundRequestedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RefundRequestedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence paymentId;
  private java.lang.CharSequence refundAmount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RefundRequestedEvent() {}

  /**
   * All-args constructor.
   * @param paymentId The new value for paymentId
   * @param refundAmount The new value for refundAmount
   */
  public RefundRequestedEvent(java.lang.CharSequence paymentId, java.lang.CharSequence refundAmount) {
    this.paymentId = paymentId;
    this.refundAmount = refundAmount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return refundAmount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: refundAmount = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'refundAmount' field.
   * @return The value of the 'refundAmount' field.
   */
  public java.lang.CharSequence getRefundAmount() {
    return refundAmount;
  }


  /**
   * Sets the value of the 'refundAmount' field.
   * @param value the value to set.
   */
  public void setRefundAmount(java.lang.CharSequence value) {
    this.refundAmount = value;
  }

  /**
   * Creates a new RefundRequestedEvent RecordBuilder.
   * @return A new RefundRequestedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RefundRequestedEvent.Builder newBuilder() {
    return new com.zaheudev.shared.avro.RefundRequestedEvent.Builder();
  }

  /**
   * Creates a new RefundRequestedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RefundRequestedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RefundRequestedEvent.Builder newBuilder(com.zaheudev.shared.avro.RefundRequestedEvent.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RefundRequestedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.RefundRequestedEvent.Builder(other);
    }
  }

  /**
   * Creates a new RefundRequestedEvent RecordBuilder by copying an existing RefundRequestedEvent instance.
   * @param other The existing instance to copy.
   * @return A new RefundRequestedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RefundRequestedEvent.Builder newBuilder(com.zaheudev.shared.avro.RefundRequestedEvent other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RefundRequestedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.RefundRequestedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RefundRequestedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RefundRequestedEvent>
    implements org.apache.avro.data.RecordBuilder<RefundRequestedEvent> {

    private java.lang.CharSequence paymentId;
    private java.lang.CharSequence refundAmount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.RefundRequestedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.refundAmount)) {
        this.refundAmount = data().deepCopy(fields()[1].schema(), other.refundAmount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing RefundRequestedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.RefundRequestedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.refundAmount)) {
        this.refundAmount = data().deepCopy(fields()[1].schema(), other.refundAmount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundRequestedEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundRequestedEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'refundAmount' field.
      * @return The value.
      */
    public java.lang.CharSequence getRefundAmount() {
      return refundAmount;
    }


    /**
      * Sets the value of the 'refundAmount' field.
      * @param value The value of 'refundAmount'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundRequestedEvent.Builder setRefundAmount(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.refundAmount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'refundAmount' field has been set.
      * @return True if the 'refundAmount' field has been set, false otherwise.
      */
    public boolean hasRefundAmount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'refundAmount' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RefundRequestedEvent.Builder clearRefundAmount() {
      refundAmount = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RefundRequestedEvent build() {
      try {
        RefundRequestedEvent record = new RefundRequestedEvent();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.refundAmount = fieldSetFlags()[1] ? this.refundAmount : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RefundRequestedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RefundRequestedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RefundRequestedEvent>
    READER$ = (org.apache.avro.io.DatumReader<RefundRequestedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.paymentId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.paymentId);
    }

    if (this.refundAmount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.refundAmount);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.paymentId = null;
      } else {
        this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.refundAmount = null;
      } else {
        this.refundAmount = in.readString(this.refundAmount instanceof Utf8 ? (Utf8)this.refundAmount : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.paymentId = null;
          } else {
            this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.refundAmount = null;
          } else {
            this.refundAmount = in.readString(this.refundAmount instanceof Utf8 ? (Utf8)this.refundAmount : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (refundAmount == null ? 0 : refundAmount.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof RefundRequestedEvent)) {
      return false;
    }
    RefundRequestedEvent other = (RefundRequestedEvent) o;
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.refundAmount, other.refundAmount) != 0) {
      return false;
    }
    return true;
  }
}










