/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;
@org.apache.avro.specific.AvroGenerated
public enum RiskLevel implements org.apache.avro.generic.GenericEnumSymbol<RiskLevel> {
  LOW, MEDIUM, HIGH, CRITICAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RiskLevel\",\"namespace\":\"com.zaheudev.shared.avro\",\"symbols\":[\"LOW\",\"MEDIUM\",\"HIGH\",\"CRITICAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
