/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RiskAssessed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8681846726463660957L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RiskAssessed\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"paymentId\",\"type\":\"string\"},{\"name\":\"riskScore\",\"type\":\"double\"},{\"name\":\"riskLevel\",\"type\":\"string\"},{\"name\":\"approved\",\"type\":\"boolean\"},{\"name\":\"reason\",\"type\":\"string\"},{\"name\":\"assessmentId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RiskAssessed> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RiskAssessed> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RiskAssessed> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RiskAssessed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RiskAssessed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RiskAssessed to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RiskAssessed from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RiskAssessed instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RiskAssessed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence paymentId;
  private double riskScore;
  private java.lang.CharSequence riskLevel;
  private boolean approved;
  private java.lang.CharSequence reason;
  private java.lang.CharSequence assessmentId;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RiskAssessed() {}

  /**
   * All-args constructor.
   * @param paymentId The new value for paymentId
   * @param riskScore The new value for riskScore
   * @param riskLevel The new value for riskLevel
   * @param approved The new value for approved
   * @param reason The new value for reason
   * @param assessmentId The new value for assessmentId
   * @param timestamp The new value for timestamp
   */
  public RiskAssessed(java.lang.CharSequence paymentId, java.lang.Double riskScore, java.lang.CharSequence riskLevel, java.lang.Boolean approved, java.lang.CharSequence reason, java.lang.CharSequence assessmentId, java.lang.Long timestamp) {
    this.paymentId = paymentId;
    this.riskScore = riskScore;
    this.riskLevel = riskLevel;
    this.approved = approved;
    this.reason = reason;
    this.assessmentId = assessmentId;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return riskScore;
    case 2: return riskLevel;
    case 3: return approved;
    case 4: return reason;
    case 5: return assessmentId;
    case 6: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: riskScore = (java.lang.Double)value$; break;
    case 2: riskLevel = (java.lang.CharSequence)value$; break;
    case 3: approved = (java.lang.Boolean)value$; break;
    case 4: reason = (java.lang.CharSequence)value$; break;
    case 5: assessmentId = (java.lang.CharSequence)value$; break;
    case 6: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'riskScore' field.
   * @return The value of the 'riskScore' field.
   */
  public double getRiskScore() {
    return riskScore;
  }


  /**
   * Sets the value of the 'riskScore' field.
   * @param value the value to set.
   */
  public void setRiskScore(double value) {
    this.riskScore = value;
  }

  /**
   * Gets the value of the 'riskLevel' field.
   * @return The value of the 'riskLevel' field.
   */
  public java.lang.CharSequence getRiskLevel() {
    return riskLevel;
  }


  /**
   * Sets the value of the 'riskLevel' field.
   * @param value the value to set.
   */
  public void setRiskLevel(java.lang.CharSequence value) {
    this.riskLevel = value;
  }

  /**
   * Gets the value of the 'approved' field.
   * @return The value of the 'approved' field.
   */
  public boolean getApproved() {
    return approved;
  }


  /**
   * Sets the value of the 'approved' field.
   * @param value the value to set.
   */
  public void setApproved(boolean value) {
    this.approved = value;
  }

  /**
   * Gets the value of the 'reason' field.
   * @return The value of the 'reason' field.
   */
  public java.lang.CharSequence getReason() {
    return reason;
  }


  /**
   * Sets the value of the 'reason' field.
   * @param value the value to set.
   */
  public void setReason(java.lang.CharSequence value) {
    this.reason = value;
  }

  /**
   * Gets the value of the 'assessmentId' field.
   * @return The value of the 'assessmentId' field.
   */
  public java.lang.CharSequence getAssessmentId() {
    return assessmentId;
  }


  /**
   * Sets the value of the 'assessmentId' field.
   * @param value the value to set.
   */
  public void setAssessmentId(java.lang.CharSequence value) {
    this.assessmentId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new RiskAssessed RecordBuilder.
   * @return A new RiskAssessed RecordBuilder
   */
  public static com.zaheudev.shared.avro.RiskAssessed.Builder newBuilder() {
    return new com.zaheudev.shared.avro.RiskAssessed.Builder();
  }

  /**
   * Creates a new RiskAssessed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RiskAssessed RecordBuilder
   */
  public static com.zaheudev.shared.avro.RiskAssessed.Builder newBuilder(com.zaheudev.shared.avro.RiskAssessed.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RiskAssessed.Builder();
    } else {
      return new com.zaheudev.shared.avro.RiskAssessed.Builder(other);
    }
  }

  /**
   * Creates a new RiskAssessed RecordBuilder by copying an existing RiskAssessed instance.
   * @param other The existing instance to copy.
   * @return A new RiskAssessed RecordBuilder
   */
  public static com.zaheudev.shared.avro.RiskAssessed.Builder newBuilder(com.zaheudev.shared.avro.RiskAssessed other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RiskAssessed.Builder();
    } else {
      return new com.zaheudev.shared.avro.RiskAssessed.Builder(other);
    }
  }

  /**
   * RecordBuilder for RiskAssessed instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RiskAssessed>
    implements org.apache.avro.data.RecordBuilder<RiskAssessed> {

    private java.lang.CharSequence paymentId;
    private double riskScore;
    private java.lang.CharSequence riskLevel;
    private boolean approved;
    private java.lang.CharSequence reason;
    private java.lang.CharSequence assessmentId;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.RiskAssessed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.riskScore)) {
        this.riskScore = data().deepCopy(fields()[1].schema(), other.riskScore);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.riskLevel)) {
        this.riskLevel = data().deepCopy(fields()[2].schema(), other.riskLevel);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.approved)) {
        this.approved = data().deepCopy(fields()[3].schema(), other.approved);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.reason)) {
        this.reason = data().deepCopy(fields()[4].schema(), other.reason);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.assessmentId)) {
        this.assessmentId = data().deepCopy(fields()[5].schema(), other.assessmentId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing RiskAssessed instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.RiskAssessed other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.riskScore)) {
        this.riskScore = data().deepCopy(fields()[1].schema(), other.riskScore);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.riskLevel)) {
        this.riskLevel = data().deepCopy(fields()[2].schema(), other.riskLevel);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.approved)) {
        this.approved = data().deepCopy(fields()[3].schema(), other.approved);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.reason)) {
        this.reason = data().deepCopy(fields()[4].schema(), other.reason);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.assessmentId)) {
        this.assessmentId = data().deepCopy(fields()[5].schema(), other.assessmentId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'riskScore' field.
      * @return The value.
      */
    public double getRiskScore() {
      return riskScore;
    }


    /**
      * Sets the value of the 'riskScore' field.
      * @param value The value of 'riskScore'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder setRiskScore(double value) {
      validate(fields()[1], value);
      this.riskScore = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'riskScore' field has been set.
      * @return True if the 'riskScore' field has been set, false otherwise.
      */
    public boolean hasRiskScore() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'riskScore' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder clearRiskScore() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'riskLevel' field.
      * @return The value.
      */
    public java.lang.CharSequence getRiskLevel() {
      return riskLevel;
    }


    /**
      * Sets the value of the 'riskLevel' field.
      * @param value The value of 'riskLevel'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder setRiskLevel(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.riskLevel = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'riskLevel' field has been set.
      * @return True if the 'riskLevel' field has been set, false otherwise.
      */
    public boolean hasRiskLevel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'riskLevel' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder clearRiskLevel() {
      riskLevel = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'approved' field.
      * @return The value.
      */
    public boolean getApproved() {
      return approved;
    }


    /**
      * Sets the value of the 'approved' field.
      * @param value The value of 'approved'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder setApproved(boolean value) {
      validate(fields()[3], value);
      this.approved = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'approved' field has been set.
      * @return True if the 'approved' field has been set, false otherwise.
      */
    public boolean hasApproved() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'approved' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder clearApproved() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'reason' field.
      * @return The value.
      */
    public java.lang.CharSequence getReason() {
      return reason;
    }


    /**
      * Sets the value of the 'reason' field.
      * @param value The value of 'reason'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder setReason(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.reason = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'reason' field has been set.
      * @return True if the 'reason' field has been set, false otherwise.
      */
    public boolean hasReason() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'reason' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder clearReason() {
      reason = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'assessmentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAssessmentId() {
      return assessmentId;
    }


    /**
      * Sets the value of the 'assessmentId' field.
      * @param value The value of 'assessmentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder setAssessmentId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.assessmentId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'assessmentId' field has been set.
      * @return True if the 'assessmentId' field has been set, false otherwise.
      */
    public boolean hasAssessmentId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'assessmentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder clearAssessmentId() {
      assessmentId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder setTimestamp(long value) {
      validate(fields()[6], value);
      this.timestamp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessed.Builder clearTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RiskAssessed build() {
      try {
        RiskAssessed record = new RiskAssessed();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.riskScore = fieldSetFlags()[1] ? this.riskScore : (java.lang.Double) defaultValue(fields()[1]);
        record.riskLevel = fieldSetFlags()[2] ? this.riskLevel : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.approved = fieldSetFlags()[3] ? this.approved : (java.lang.Boolean) defaultValue(fields()[3]);
        record.reason = fieldSetFlags()[4] ? this.reason : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.assessmentId = fieldSetFlags()[5] ? this.assessmentId : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.timestamp = fieldSetFlags()[6] ? this.timestamp : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RiskAssessed>
    WRITER$ = (org.apache.avro.io.DatumWriter<RiskAssessed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RiskAssessed>
    READER$ = (org.apache.avro.io.DatumReader<RiskAssessed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentId);

    out.writeDouble(this.riskScore);

    out.writeString(this.riskLevel);

    out.writeBoolean(this.approved);

    out.writeString(this.reason);

    out.writeString(this.assessmentId);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);

      this.riskScore = in.readDouble();

      this.riskLevel = in.readString(this.riskLevel instanceof Utf8 ? (Utf8)this.riskLevel : null);

      this.approved = in.readBoolean();

      this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);

      this.assessmentId = in.readString(this.assessmentId instanceof Utf8 ? (Utf8)this.assessmentId : null);

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          break;

        case 1:
          this.riskScore = in.readDouble();
          break;

        case 2:
          this.riskLevel = in.readString(this.riskLevel instanceof Utf8 ? (Utf8)this.riskLevel : null);
          break;

        case 3:
          this.approved = in.readBoolean();
          break;

        case 4:
          this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);
          break;

        case 5:
          this.assessmentId = in.readString(this.assessmentId instanceof Utf8 ? (Utf8)this.assessmentId : null);
          break;

        case 6:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + Double.hashCode(riskScore);
    result = 31 * result + (riskLevel == null ? 0 : riskLevel.hashCode());
    result = 31 * result + Boolean.hashCode(approved);
    result = 31 * result + (reason == null ? 0 : reason.hashCode());
    result = 31 * result + (assessmentId == null ? 0 : assessmentId.hashCode());
    result = 31 * result + Long.hashCode(timestamp);
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof RiskAssessed)) {
      return false;
    }
    RiskAssessed other = (RiskAssessed) o;
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (this.riskScore != other.riskScore) {
      return false;
    }
    if (Utf8.compareSequences(this.riskLevel, other.riskLevel) != 0) {
      return false;
    }
    if (this.approved != other.approved) {
      return false;
    }
    if (Utf8.compareSequences(this.reason, other.reason) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.assessmentId, other.assessmentId) != 0) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    return true;
  }
}










