/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RiskAssessedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4739948810926017816L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RiskAssessedEvent\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"paymentId\",\"type\":\"string\"},{\"name\":\"riskLevel\",\"type\":{\"type\":\"enum\",\"name\":\"RiskLevel\",\"symbols\":[\"LOW\",\"MEDIUM\",\"HIGH\",\"CRITICAL\"]}},{\"name\":\"approved\",\"type\":\"boolean\"},{\"name\":\"reason\",\"type\":\"string\"},{\"name\":\"assessmentId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"cardRecord\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"CardRecord\",\"fields\":[{\"name\":\"tokenRef\",\"type\":\"string\",\"doc\":\"This is the token for the card details\"},{\"name\":\"tokenValue\",\"type\":[\"null\",\"string\"],\"doc\":\"This is the network token value\",\"default\":null},{\"name\":\"bin\",\"type\":\"string\",\"doc\":\"The first 6 digits of the card number\"},{\"name\":\"lastFour\",\"type\":\"string\"},{\"name\":\"primaryNetwork\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"PaymentMethodEnum\",\"symbols\":[\"VISA\",\"MASTERCARD\",\"AMEX\",\"DISCOVER\",\"ACCEL\",\"STAR\",\"NYCE\",\"PULSE\",\"MAESTRO\"]}],\"default\":null},{\"name\":\"cardType\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"amount\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Amount\",\"fields\":[{\"name\":\"value\",\"type\":\"long\",\"doc\":\"Suma tranzacției exprimată în cea mai mică unitate monetară (de exemplu, bani pentru RON, cenți pentru EUR/USD)\"},{\"name\":\"currency\",\"type\":\"string\",\"doc\":\"Moneda (RON, EUR, USD)\"}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RiskAssessedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RiskAssessedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RiskAssessedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RiskAssessedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RiskAssessedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RiskAssessedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RiskAssessedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RiskAssessedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RiskAssessedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence paymentId;
  private com.zaheudev.shared.avro.RiskLevel riskLevel;
  private boolean approved;
  private java.lang.CharSequence reason;
  private java.lang.CharSequence assessmentId;
  private long timestamp;
  private com.zaheudev.shared.avro.CardRecord cardRecord;
  private com.zaheudev.shared.avro.Amount amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RiskAssessedEvent() {}

  /**
   * All-args constructor.
   * @param paymentId The new value for paymentId
   * @param riskLevel The new value for riskLevel
   * @param approved The new value for approved
   * @param reason The new value for reason
   * @param assessmentId The new value for assessmentId
   * @param timestamp The new value for timestamp
   * @param cardRecord The new value for cardRecord
   * @param amount The new value for amount
   */
  public RiskAssessedEvent(java.lang.CharSequence paymentId, com.zaheudev.shared.avro.RiskLevel riskLevel, java.lang.Boolean approved, java.lang.CharSequence reason, java.lang.CharSequence assessmentId, java.lang.Long timestamp, com.zaheudev.shared.avro.CardRecord cardRecord, com.zaheudev.shared.avro.Amount amount) {
    this.paymentId = paymentId;
    this.riskLevel = riskLevel;
    this.approved = approved;
    this.reason = reason;
    this.assessmentId = assessmentId;
    this.timestamp = timestamp;
    this.cardRecord = cardRecord;
    this.amount = amount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return riskLevel;
    case 2: return approved;
    case 3: return reason;
    case 4: return assessmentId;
    case 5: return timestamp;
    case 6: return cardRecord;
    case 7: return amount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: riskLevel = (com.zaheudev.shared.avro.RiskLevel)value$; break;
    case 2: approved = (java.lang.Boolean)value$; break;
    case 3: reason = (java.lang.CharSequence)value$; break;
    case 4: assessmentId = (java.lang.CharSequence)value$; break;
    case 5: timestamp = (java.lang.Long)value$; break;
    case 6: cardRecord = (com.zaheudev.shared.avro.CardRecord)value$; break;
    case 7: amount = (com.zaheudev.shared.avro.Amount)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'riskLevel' field.
   * @return The value of the 'riskLevel' field.
   */
  public com.zaheudev.shared.avro.RiskLevel getRiskLevel() {
    return riskLevel;
  }


  /**
   * Sets the value of the 'riskLevel' field.
   * @param value the value to set.
   */
  public void setRiskLevel(com.zaheudev.shared.avro.RiskLevel value) {
    this.riskLevel = value;
  }

  /**
   * Gets the value of the 'approved' field.
   * @return The value of the 'approved' field.
   */
  public boolean getApproved() {
    return approved;
  }


  /**
   * Sets the value of the 'approved' field.
   * @param value the value to set.
   */
  public void setApproved(boolean value) {
    this.approved = value;
  }

  /**
   * Gets the value of the 'reason' field.
   * @return The value of the 'reason' field.
   */
  public java.lang.CharSequence getReason() {
    return reason;
  }


  /**
   * Sets the value of the 'reason' field.
   * @param value the value to set.
   */
  public void setReason(java.lang.CharSequence value) {
    this.reason = value;
  }

  /**
   * Gets the value of the 'assessmentId' field.
   * @return The value of the 'assessmentId' field.
   */
  public java.lang.CharSequence getAssessmentId() {
    return assessmentId;
  }


  /**
   * Sets the value of the 'assessmentId' field.
   * @param value the value to set.
   */
  public void setAssessmentId(java.lang.CharSequence value) {
    this.assessmentId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'cardRecord' field.
   * @return The value of the 'cardRecord' field.
   */
  public com.zaheudev.shared.avro.CardRecord getCardRecord() {
    return cardRecord;
  }


  /**
   * Sets the value of the 'cardRecord' field.
   * @param value the value to set.
   */
  public void setCardRecord(com.zaheudev.shared.avro.CardRecord value) {
    this.cardRecord = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public com.zaheudev.shared.avro.Amount getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(com.zaheudev.shared.avro.Amount value) {
    this.amount = value;
  }

  /**
   * Creates a new RiskAssessedEvent RecordBuilder.
   * @return A new RiskAssessedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RiskAssessedEvent.Builder newBuilder() {
    return new com.zaheudev.shared.avro.RiskAssessedEvent.Builder();
  }

  /**
   * Creates a new RiskAssessedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RiskAssessedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RiskAssessedEvent.Builder newBuilder(com.zaheudev.shared.avro.RiskAssessedEvent.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RiskAssessedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.RiskAssessedEvent.Builder(other);
    }
  }

  /**
   * Creates a new RiskAssessedEvent RecordBuilder by copying an existing RiskAssessedEvent instance.
   * @param other The existing instance to copy.
   * @return A new RiskAssessedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RiskAssessedEvent.Builder newBuilder(com.zaheudev.shared.avro.RiskAssessedEvent other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RiskAssessedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.RiskAssessedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RiskAssessedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RiskAssessedEvent>
    implements org.apache.avro.data.RecordBuilder<RiskAssessedEvent> {

    private java.lang.CharSequence paymentId;
    private com.zaheudev.shared.avro.RiskLevel riskLevel;
    private boolean approved;
    private java.lang.CharSequence reason;
    private java.lang.CharSequence assessmentId;
    private long timestamp;
    private com.zaheudev.shared.avro.CardRecord cardRecord;
    private com.zaheudev.shared.avro.CardRecord.Builder cardRecordBuilder;
    private com.zaheudev.shared.avro.Amount amount;
    private com.zaheudev.shared.avro.Amount.Builder amountBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.RiskAssessedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.riskLevel)) {
        this.riskLevel = data().deepCopy(fields()[1].schema(), other.riskLevel);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.approved)) {
        this.approved = data().deepCopy(fields()[2].schema(), other.approved);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.reason)) {
        this.reason = data().deepCopy(fields()[3].schema(), other.reason);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.assessmentId)) {
        this.assessmentId = data().deepCopy(fields()[4].schema(), other.assessmentId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.cardRecord)) {
        this.cardRecord = data().deepCopy(fields()[6].schema(), other.cardRecord);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (other.hasCardRecordBuilder()) {
        this.cardRecordBuilder = com.zaheudev.shared.avro.CardRecord.newBuilder(other.getCardRecordBuilder());
      }
      if (isValidValue(fields()[7], other.amount)) {
        this.amount = data().deepCopy(fields()[7].schema(), other.amount);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (other.hasAmountBuilder()) {
        this.amountBuilder = com.zaheudev.shared.avro.Amount.newBuilder(other.getAmountBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing RiskAssessedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.RiskAssessedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.riskLevel)) {
        this.riskLevel = data().deepCopy(fields()[1].schema(), other.riskLevel);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.approved)) {
        this.approved = data().deepCopy(fields()[2].schema(), other.approved);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.reason)) {
        this.reason = data().deepCopy(fields()[3].schema(), other.reason);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.assessmentId)) {
        this.assessmentId = data().deepCopy(fields()[4].schema(), other.assessmentId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cardRecord)) {
        this.cardRecord = data().deepCopy(fields()[6].schema(), other.cardRecord);
        fieldSetFlags()[6] = true;
      }
      this.cardRecordBuilder = null;
      if (isValidValue(fields()[7], other.amount)) {
        this.amount = data().deepCopy(fields()[7].schema(), other.amount);
        fieldSetFlags()[7] = true;
      }
      this.amountBuilder = null;
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'riskLevel' field.
      * @return The value.
      */
    public com.zaheudev.shared.avro.RiskLevel getRiskLevel() {
      return riskLevel;
    }


    /**
      * Sets the value of the 'riskLevel' field.
      * @param value The value of 'riskLevel'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setRiskLevel(com.zaheudev.shared.avro.RiskLevel value) {
      validate(fields()[1], value);
      this.riskLevel = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'riskLevel' field has been set.
      * @return True if the 'riskLevel' field has been set, false otherwise.
      */
    public boolean hasRiskLevel() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'riskLevel' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder clearRiskLevel() {
      riskLevel = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'approved' field.
      * @return The value.
      */
    public boolean getApproved() {
      return approved;
    }


    /**
      * Sets the value of the 'approved' field.
      * @param value The value of 'approved'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setApproved(boolean value) {
      validate(fields()[2], value);
      this.approved = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'approved' field has been set.
      * @return True if the 'approved' field has been set, false otherwise.
      */
    public boolean hasApproved() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'approved' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder clearApproved() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'reason' field.
      * @return The value.
      */
    public java.lang.CharSequence getReason() {
      return reason;
    }


    /**
      * Sets the value of the 'reason' field.
      * @param value The value of 'reason'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setReason(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.reason = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'reason' field has been set.
      * @return True if the 'reason' field has been set, false otherwise.
      */
    public boolean hasReason() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'reason' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder clearReason() {
      reason = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'assessmentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAssessmentId() {
      return assessmentId;
    }


    /**
      * Sets the value of the 'assessmentId' field.
      * @param value The value of 'assessmentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setAssessmentId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.assessmentId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'assessmentId' field has been set.
      * @return True if the 'assessmentId' field has been set, false otherwise.
      */
    public boolean hasAssessmentId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'assessmentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder clearAssessmentId() {
      assessmentId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setTimestamp(long value) {
      validate(fields()[5], value);
      this.timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'cardRecord' field.
      * @return The value.
      */
    public com.zaheudev.shared.avro.CardRecord getCardRecord() {
      return cardRecord;
    }


    /**
      * Sets the value of the 'cardRecord' field.
      * @param value The value of 'cardRecord'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setCardRecord(com.zaheudev.shared.avro.CardRecord value) {
      validate(fields()[6], value);
      this.cardRecordBuilder = null;
      this.cardRecord = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'cardRecord' field has been set.
      * @return True if the 'cardRecord' field has been set, false otherwise.
      */
    public boolean hasCardRecord() {
      return fieldSetFlags()[6];
    }

    /**
     * Gets the Builder instance for the 'cardRecord' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.zaheudev.shared.avro.CardRecord.Builder getCardRecordBuilder() {
      if (cardRecordBuilder == null) {
        if (hasCardRecord()) {
          setCardRecordBuilder(com.zaheudev.shared.avro.CardRecord.newBuilder(cardRecord));
        } else {
          setCardRecordBuilder(com.zaheudev.shared.avro.CardRecord.newBuilder());
        }
      }
      return cardRecordBuilder;
    }

    /**
     * Sets the Builder instance for the 'cardRecord' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setCardRecordBuilder(com.zaheudev.shared.avro.CardRecord.Builder value) {
      clearCardRecord();
      cardRecordBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'cardRecord' field has an active Builder instance
     * @return True if the 'cardRecord' field has an active Builder instance
     */
    public boolean hasCardRecordBuilder() {
      return cardRecordBuilder != null;
    }

    /**
      * Clears the value of the 'cardRecord' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder clearCardRecord() {
      cardRecord = null;
      cardRecordBuilder = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public com.zaheudev.shared.avro.Amount getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setAmount(com.zaheudev.shared.avro.Amount value) {
      validate(fields()[7], value);
      this.amountBuilder = null;
      this.amount = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[7];
    }

    /**
     * Gets the Builder instance for the 'amount' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.zaheudev.shared.avro.Amount.Builder getAmountBuilder() {
      if (amountBuilder == null) {
        if (hasAmount()) {
          setAmountBuilder(com.zaheudev.shared.avro.Amount.newBuilder(amount));
        } else {
          setAmountBuilder(com.zaheudev.shared.avro.Amount.newBuilder());
        }
      }
      return amountBuilder;
    }

    /**
     * Sets the Builder instance for the 'amount' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder setAmountBuilder(com.zaheudev.shared.avro.Amount.Builder value) {
      clearAmount();
      amountBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'amount' field has an active Builder instance
     * @return True if the 'amount' field has an active Builder instance
     */
    public boolean hasAmountBuilder() {
      return amountBuilder != null;
    }

    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RiskAssessedEvent.Builder clearAmount() {
      amount = null;
      amountBuilder = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RiskAssessedEvent build() {
      try {
        RiskAssessedEvent record = new RiskAssessedEvent();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.riskLevel = fieldSetFlags()[1] ? this.riskLevel : (com.zaheudev.shared.avro.RiskLevel) defaultValue(fields()[1]);
        record.approved = fieldSetFlags()[2] ? this.approved : (java.lang.Boolean) defaultValue(fields()[2]);
        record.reason = fieldSetFlags()[3] ? this.reason : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.assessmentId = fieldSetFlags()[4] ? this.assessmentId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.lang.Long) defaultValue(fields()[5]);
        if (cardRecordBuilder != null) {
          try {
            record.cardRecord = this.cardRecordBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("cardRecord"));
            throw e;
          }
        } else {
          record.cardRecord = fieldSetFlags()[6] ? this.cardRecord : (com.zaheudev.shared.avro.CardRecord) defaultValue(fields()[6]);
        }
        if (amountBuilder != null) {
          try {
            record.amount = this.amountBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("amount"));
            throw e;
          }
        } else {
          record.amount = fieldSetFlags()[7] ? this.amount : (com.zaheudev.shared.avro.Amount) defaultValue(fields()[7]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RiskAssessedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RiskAssessedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RiskAssessedEvent>
    READER$ = (org.apache.avro.io.DatumReader<RiskAssessedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentId);

    out.writeEnum(this.riskLevel.ordinal());

    out.writeBoolean(this.approved);

    out.writeString(this.reason);

    out.writeString(this.assessmentId);

    out.writeLong(this.timestamp);

    if (this.cardRecord == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.cardRecord.customEncode(out);
    }

    if (this.amount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.amount.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);

      this.riskLevel = com.zaheudev.shared.avro.RiskLevel.values()[in.readEnum()];

      this.approved = in.readBoolean();

      this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);

      this.assessmentId = in.readString(this.assessmentId instanceof Utf8 ? (Utf8)this.assessmentId : null);

      this.timestamp = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.cardRecord = null;
      } else {
        if (this.cardRecord == null) {
          this.cardRecord = new com.zaheudev.shared.avro.CardRecord();
        }
        this.cardRecord.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.amount = null;
      } else {
        if (this.amount == null) {
          this.amount = new com.zaheudev.shared.avro.Amount();
        }
        this.amount.customDecode(in);
      }

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          break;

        case 1:
          this.riskLevel = com.zaheudev.shared.avro.RiskLevel.values()[in.readEnum()];
          break;

        case 2:
          this.approved = in.readBoolean();
          break;

        case 3:
          this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);
          break;

        case 4:
          this.assessmentId = in.readString(this.assessmentId instanceof Utf8 ? (Utf8)this.assessmentId : null);
          break;

        case 5:
          this.timestamp = in.readLong();
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.cardRecord = null;
          } else {
            if (this.cardRecord == null) {
              this.cardRecord = new com.zaheudev.shared.avro.CardRecord();
            }
            this.cardRecord.customDecode(in);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.amount = null;
          } else {
            if (this.amount == null) {
              this.amount = new com.zaheudev.shared.avro.Amount();
            }
            this.amount.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (riskLevel == null ? 0 : ((java.lang.Enum) riskLevel).ordinal());
    result = 31 * result + Boolean.hashCode(approved);
    result = 31 * result + (reason == null ? 0 : reason.hashCode());
    result = 31 * result + (assessmentId == null ? 0 : assessmentId.hashCode());
    result = 31 * result + Long.hashCode(timestamp);
    result = 31 * result + (cardRecord == null ? 0 : cardRecord.hashCode());
    result = 31 * result + (amount == null ? 0 : amount.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof RiskAssessedEvent)) {
      return false;
    }
    RiskAssessedEvent other = (RiskAssessedEvent) o;
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.riskLevel, other.riskLevel)) {
      return false;
    }
    if (this.approved != other.approved) {
      return false;
    }
    if (Utf8.compareSequences(this.reason, other.reason) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.assessmentId, other.assessmentId) != 0) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    if (!java.util.Objects.equals(this.cardRecord, other.cardRecord)) {
      return false;
    }
    if (!java.util.Objects.equals(this.amount, other.amount)) {
      return false;
    }
    return true;
  }
}










