/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RoutedCompletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6213366769668265021L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RoutedCompletedEvent\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"paymentId\",\"type\":\"string\"},{\"name\":\"selectedPaymentMethod\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentMethodEnum\",\"symbols\":[\"VISA\",\"MASTERCARD\",\"AMEX\",\"DISCOVER\",\"ACCEL\",\"STAR\",\"NYCE\",\"PULSE\",\"MAESTRO\"]}},{\"name\":\"estimatedCost\",\"type\":\"string\"},{\"name\":\"useToken\",\"type\":\"boolean\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"availableNetworks\",\"type\":{\"type\":\"array\",\"items\":\"PaymentMethodEnum\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RoutedCompletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RoutedCompletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RoutedCompletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RoutedCompletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RoutedCompletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RoutedCompletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RoutedCompletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RoutedCompletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RoutedCompletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence paymentId;
  private com.zaheudev.shared.avro.PaymentMethodEnum selectedPaymentMethod;
  private java.lang.CharSequence estimatedCost;
  private boolean useToken;
  private long timestamp;
  private java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> availableNetworks;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RoutedCompletedEvent() {}

  /**
   * All-args constructor.
   * @param paymentId The new value for paymentId
   * @param selectedPaymentMethod The new value for selectedPaymentMethod
   * @param estimatedCost The new value for estimatedCost
   * @param useToken The new value for useToken
   * @param timestamp The new value for timestamp
   * @param availableNetworks The new value for availableNetworks
   */
  public RoutedCompletedEvent(java.lang.CharSequence paymentId, com.zaheudev.shared.avro.PaymentMethodEnum selectedPaymentMethod, java.lang.CharSequence estimatedCost, java.lang.Boolean useToken, java.lang.Long timestamp, java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> availableNetworks) {
    this.paymentId = paymentId;
    this.selectedPaymentMethod = selectedPaymentMethod;
    this.estimatedCost = estimatedCost;
    this.useToken = useToken;
    this.timestamp = timestamp;
    this.availableNetworks = availableNetworks;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentId;
    case 1: return selectedPaymentMethod;
    case 2: return estimatedCost;
    case 3: return useToken;
    case 4: return timestamp;
    case 5: return availableNetworks;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentId = (java.lang.CharSequence)value$; break;
    case 1: selectedPaymentMethod = (com.zaheudev.shared.avro.PaymentMethodEnum)value$; break;
    case 2: estimatedCost = (java.lang.CharSequence)value$; break;
    case 3: useToken = (java.lang.Boolean)value$; break;
    case 4: timestamp = (java.lang.Long)value$; break;
    case 5: availableNetworks = (java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'selectedPaymentMethod' field.
   * @return The value of the 'selectedPaymentMethod' field.
   */
  public com.zaheudev.shared.avro.PaymentMethodEnum getSelectedPaymentMethod() {
    return selectedPaymentMethod;
  }


  /**
   * Sets the value of the 'selectedPaymentMethod' field.
   * @param value the value to set.
   */
  public void setSelectedPaymentMethod(com.zaheudev.shared.avro.PaymentMethodEnum value) {
    this.selectedPaymentMethod = value;
  }

  /**
   * Gets the value of the 'estimatedCost' field.
   * @return The value of the 'estimatedCost' field.
   */
  public java.lang.CharSequence getEstimatedCost() {
    return estimatedCost;
  }


  /**
   * Sets the value of the 'estimatedCost' field.
   * @param value the value to set.
   */
  public void setEstimatedCost(java.lang.CharSequence value) {
    this.estimatedCost = value;
  }

  /**
   * Gets the value of the 'useToken' field.
   * @return The value of the 'useToken' field.
   */
  public boolean getUseToken() {
    return useToken;
  }


  /**
   * Sets the value of the 'useToken' field.
   * @param value the value to set.
   */
  public void setUseToken(boolean value) {
    this.useToken = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'availableNetworks' field.
   * @return The value of the 'availableNetworks' field.
   */
  public java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> getAvailableNetworks() {
    return availableNetworks;
  }


  /**
   * Sets the value of the 'availableNetworks' field.
   * @param value the value to set.
   */
  public void setAvailableNetworks(java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> value) {
    this.availableNetworks = value;
  }

  /**
   * Creates a new RoutedCompletedEvent RecordBuilder.
   * @return A new RoutedCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RoutedCompletedEvent.Builder newBuilder() {
    return new com.zaheudev.shared.avro.RoutedCompletedEvent.Builder();
  }

  /**
   * Creates a new RoutedCompletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RoutedCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RoutedCompletedEvent.Builder newBuilder(com.zaheudev.shared.avro.RoutedCompletedEvent.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RoutedCompletedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.RoutedCompletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new RoutedCompletedEvent RecordBuilder by copying an existing RoutedCompletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new RoutedCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.RoutedCompletedEvent.Builder newBuilder(com.zaheudev.shared.avro.RoutedCompletedEvent other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.RoutedCompletedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.RoutedCompletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RoutedCompletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RoutedCompletedEvent>
    implements org.apache.avro.data.RecordBuilder<RoutedCompletedEvent> {

    private java.lang.CharSequence paymentId;
    private com.zaheudev.shared.avro.PaymentMethodEnum selectedPaymentMethod;
    private java.lang.CharSequence estimatedCost;
    private boolean useToken;
    private long timestamp;
    private java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> availableNetworks;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.RoutedCompletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.selectedPaymentMethod)) {
        this.selectedPaymentMethod = data().deepCopy(fields()[1].schema(), other.selectedPaymentMethod);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.estimatedCost)) {
        this.estimatedCost = data().deepCopy(fields()[2].schema(), other.estimatedCost);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.useToken)) {
        this.useToken = data().deepCopy(fields()[3].schema(), other.useToken);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.availableNetworks)) {
        this.availableNetworks = data().deepCopy(fields()[5].schema(), other.availableNetworks);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing RoutedCompletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.RoutedCompletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[0].schema(), other.paymentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.selectedPaymentMethod)) {
        this.selectedPaymentMethod = data().deepCopy(fields()[1].schema(), other.selectedPaymentMethod);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.estimatedCost)) {
        this.estimatedCost = data().deepCopy(fields()[2].schema(), other.estimatedCost);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.useToken)) {
        this.useToken = data().deepCopy(fields()[3].schema(), other.useToken);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.availableNetworks)) {
        this.availableNetworks = data().deepCopy(fields()[5].schema(), other.availableNetworks);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'selectedPaymentMethod' field.
      * @return The value.
      */
    public com.zaheudev.shared.avro.PaymentMethodEnum getSelectedPaymentMethod() {
      return selectedPaymentMethod;
    }


    /**
      * Sets the value of the 'selectedPaymentMethod' field.
      * @param value The value of 'selectedPaymentMethod'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder setSelectedPaymentMethod(com.zaheudev.shared.avro.PaymentMethodEnum value) {
      validate(fields()[1], value);
      this.selectedPaymentMethod = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'selectedPaymentMethod' field has been set.
      * @return True if the 'selectedPaymentMethod' field has been set, false otherwise.
      */
    public boolean hasSelectedPaymentMethod() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'selectedPaymentMethod' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder clearSelectedPaymentMethod() {
      selectedPaymentMethod = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'estimatedCost' field.
      * @return The value.
      */
    public java.lang.CharSequence getEstimatedCost() {
      return estimatedCost;
    }


    /**
      * Sets the value of the 'estimatedCost' field.
      * @param value The value of 'estimatedCost'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder setEstimatedCost(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.estimatedCost = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'estimatedCost' field has been set.
      * @return True if the 'estimatedCost' field has been set, false otherwise.
      */
    public boolean hasEstimatedCost() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'estimatedCost' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder clearEstimatedCost() {
      estimatedCost = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'useToken' field.
      * @return The value.
      */
    public boolean getUseToken() {
      return useToken;
    }


    /**
      * Sets the value of the 'useToken' field.
      * @param value The value of 'useToken'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder setUseToken(boolean value) {
      validate(fields()[3], value);
      this.useToken = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'useToken' field has been set.
      * @return True if the 'useToken' field has been set, false otherwise.
      */
    public boolean hasUseToken() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'useToken' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder clearUseToken() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'availableNetworks' field.
      * @return The value.
      */
    public java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> getAvailableNetworks() {
      return availableNetworks;
    }


    /**
      * Sets the value of the 'availableNetworks' field.
      * @param value The value of 'availableNetworks'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder setAvailableNetworks(java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> value) {
      validate(fields()[5], value);
      this.availableNetworks = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'availableNetworks' field has been set.
      * @return True if the 'availableNetworks' field has been set, false otherwise.
      */
    public boolean hasAvailableNetworks() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'availableNetworks' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.RoutedCompletedEvent.Builder clearAvailableNetworks() {
      availableNetworks = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RoutedCompletedEvent build() {
      try {
        RoutedCompletedEvent record = new RoutedCompletedEvent();
        record.paymentId = fieldSetFlags()[0] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.selectedPaymentMethod = fieldSetFlags()[1] ? this.selectedPaymentMethod : (com.zaheudev.shared.avro.PaymentMethodEnum) defaultValue(fields()[1]);
        record.estimatedCost = fieldSetFlags()[2] ? this.estimatedCost : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.useToken = fieldSetFlags()[3] ? this.useToken : (java.lang.Boolean) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.availableNetworks = fieldSetFlags()[5] ? this.availableNetworks : (java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum>) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RoutedCompletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RoutedCompletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RoutedCompletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<RoutedCompletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentId);

    out.writeEnum(this.selectedPaymentMethod.ordinal());

    out.writeString(this.estimatedCost);

    out.writeBoolean(this.useToken);

    out.writeLong(this.timestamp);

    long size0 = this.availableNetworks.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.zaheudev.shared.avro.PaymentMethodEnum e0: this.availableNetworks) {
      actualSize0++;
      out.startItem();
      out.writeEnum(e0.ordinal());
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);

      this.selectedPaymentMethod = com.zaheudev.shared.avro.PaymentMethodEnum.values()[in.readEnum()];

      this.estimatedCost = in.readString(this.estimatedCost instanceof Utf8 ? (Utf8)this.estimatedCost : null);

      this.useToken = in.readBoolean();

      this.timestamp = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> a0 = this.availableNetworks;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.zaheudev.shared.avro.PaymentMethodEnum>((int)size0, SCHEMA$.getField("availableNetworks").schema());
        this.availableNetworks = a0;
      } else a0.clear();
      SpecificData.Array<com.zaheudev.shared.avro.PaymentMethodEnum> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.zaheudev.shared.avro.PaymentMethodEnum>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.zaheudev.shared.avro.PaymentMethodEnum e0 = (ga0 != null ? ga0.peek() : null);
          e0 = com.zaheudev.shared.avro.PaymentMethodEnum.values()[in.readEnum()];
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          break;

        case 1:
          this.selectedPaymentMethod = com.zaheudev.shared.avro.PaymentMethodEnum.values()[in.readEnum()];
          break;

        case 2:
          this.estimatedCost = in.readString(this.estimatedCost instanceof Utf8 ? (Utf8)this.estimatedCost : null);
          break;

        case 3:
          this.useToken = in.readBoolean();
          break;

        case 4:
          this.timestamp = in.readLong();
          break;

        case 5:
          long size0 = in.readArrayStart();
          java.util.List<com.zaheudev.shared.avro.PaymentMethodEnum> a0 = this.availableNetworks;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.zaheudev.shared.avro.PaymentMethodEnum>((int)size0, SCHEMA$.getField("availableNetworks").schema());
            this.availableNetworks = a0;
          } else a0.clear();
          SpecificData.Array<com.zaheudev.shared.avro.PaymentMethodEnum> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.zaheudev.shared.avro.PaymentMethodEnum>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.zaheudev.shared.avro.PaymentMethodEnum e0 = (ga0 != null ? ga0.peek() : null);
              e0 = com.zaheudev.shared.avro.PaymentMethodEnum.values()[in.readEnum()];
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (selectedPaymentMethod == null ? 0 : ((java.lang.Enum) selectedPaymentMethod).ordinal());
    result = 31 * result + (estimatedCost == null ? 0 : estimatedCost.hashCode());
    result = 31 * result + Boolean.hashCode(useToken);
    result = 31 * result + Long.hashCode(timestamp);
    result = 31 * result + (availableNetworks == null ? 0 : availableNetworks.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof RoutedCompletedEvent)) {
      return false;
    }
    RoutedCompletedEvent other = (RoutedCompletedEvent) o;
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.selectedPaymentMethod, other.selectedPaymentMethod)) {
      return false;
    }
    if (Utf8.compareSequences(this.estimatedCost, other.estimatedCost) != 0) {
      return false;
    }
    if (this.useToken != other.useToken) {
      return false;
    }
    if (this.timestamp != other.timestamp) {
      return false;
    }
    if (!java.util.Objects.equals(this.availableNetworks, other.availableNetworks)) {
      return false;
    }
    return true;
  }
}










