/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zaheudev.shared.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class VoidCompletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6603253089066092435L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VoidCompletedEvent\",\"namespace\":\"com.zaheudev.shared.avro\",\"fields\":[{\"name\":\"success\",\"type\":[\"null\",\"boolean\"],\"default\":false},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"paymentId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"processortransactionId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"errorMessage\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"timestamp\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<VoidCompletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VoidCompletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<VoidCompletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<VoidCompletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<VoidCompletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this VoidCompletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a VoidCompletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a VoidCompletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static VoidCompletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Boolean success;
  private java.lang.CharSequence status;
  private java.lang.CharSequence paymentId;
  private java.lang.CharSequence processortransactionId;
  private java.lang.CharSequence errorMessage;
  private java.lang.Long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VoidCompletedEvent() {}

  /**
   * All-args constructor.
   * @param success The new value for success
   * @param status The new value for status
   * @param paymentId The new value for paymentId
   * @param processortransactionId The new value for processortransactionId
   * @param errorMessage The new value for errorMessage
   * @param timestamp The new value for timestamp
   */
  public VoidCompletedEvent(java.lang.Boolean success, java.lang.CharSequence status, java.lang.CharSequence paymentId, java.lang.CharSequence processortransactionId, java.lang.CharSequence errorMessage, java.lang.Long timestamp) {
    this.success = success;
    this.status = status;
    this.paymentId = paymentId;
    this.processortransactionId = processortransactionId;
    this.errorMessage = errorMessage;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return success;
    case 1: return status;
    case 2: return paymentId;
    case 3: return processortransactionId;
    case 4: return errorMessage;
    case 5: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: success = (java.lang.Boolean)value$; break;
    case 1: status = (java.lang.CharSequence)value$; break;
    case 2: paymentId = (java.lang.CharSequence)value$; break;
    case 3: processortransactionId = (java.lang.CharSequence)value$; break;
    case 4: errorMessage = (java.lang.CharSequence)value$; break;
    case 5: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'success' field.
   * @return The value of the 'success' field.
   */
  public java.lang.Boolean getSuccess() {
    return success;
  }


  /**
   * Sets the value of the 'success' field.
   * @param value the value to set.
   */
  public void setSuccess(java.lang.Boolean value) {
    this.success = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'processortransactionId' field.
   * @return The value of the 'processortransactionId' field.
   */
  public java.lang.CharSequence getProcessortransactionId() {
    return processortransactionId;
  }


  /**
   * Sets the value of the 'processortransactionId' field.
   * @param value the value to set.
   */
  public void setProcessortransactionId(java.lang.CharSequence value) {
    this.processortransactionId = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.CharSequence getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.CharSequence value) {
    this.errorMessage = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new VoidCompletedEvent RecordBuilder.
   * @return A new VoidCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.VoidCompletedEvent.Builder newBuilder() {
    return new com.zaheudev.shared.avro.VoidCompletedEvent.Builder();
  }

  /**
   * Creates a new VoidCompletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VoidCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.VoidCompletedEvent.Builder newBuilder(com.zaheudev.shared.avro.VoidCompletedEvent.Builder other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.VoidCompletedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.VoidCompletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new VoidCompletedEvent RecordBuilder by copying an existing VoidCompletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new VoidCompletedEvent RecordBuilder
   */
  public static com.zaheudev.shared.avro.VoidCompletedEvent.Builder newBuilder(com.zaheudev.shared.avro.VoidCompletedEvent other) {
    if (other == null) {
      return new com.zaheudev.shared.avro.VoidCompletedEvent.Builder();
    } else {
      return new com.zaheudev.shared.avro.VoidCompletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for VoidCompletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VoidCompletedEvent>
    implements org.apache.avro.data.RecordBuilder<VoidCompletedEvent> {

    private java.lang.Boolean success;
    private java.lang.CharSequence status;
    private java.lang.CharSequence paymentId;
    private java.lang.CharSequence processortransactionId;
    private java.lang.CharSequence errorMessage;
    private java.lang.Long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zaheudev.shared.avro.VoidCompletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.success)) {
        this.success = data().deepCopy(fields()[0].schema(), other.success);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[2].schema(), other.paymentId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.processortransactionId)) {
        this.processortransactionId = data().deepCopy(fields()[3].schema(), other.processortransactionId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[4].schema(), other.errorMessage);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing VoidCompletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zaheudev.shared.avro.VoidCompletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.success)) {
        this.success = data().deepCopy(fields()[0].schema(), other.success);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[2].schema(), other.paymentId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.processortransactionId)) {
        this.processortransactionId = data().deepCopy(fields()[3].schema(), other.processortransactionId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[4].schema(), other.errorMessage);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'success' field.
      * @return The value.
      */
    public java.lang.Boolean getSuccess() {
      return success;
    }


    /**
      * Sets the value of the 'success' field.
      * @param value The value of 'success'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder setSuccess(java.lang.Boolean value) {
      validate(fields()[0], value);
      this.success = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'success' field has been set.
      * @return True if the 'success' field has been set, false otherwise.
      */
    public boolean hasSuccess() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'success' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder clearSuccess() {
      success = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.paymentId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'processortransactionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProcessortransactionId() {
      return processortransactionId;
    }


    /**
      * Sets the value of the 'processortransactionId' field.
      * @param value The value of 'processortransactionId'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder setProcessortransactionId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.processortransactionId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'processortransactionId' field has been set.
      * @return True if the 'processortransactionId' field has been set, false otherwise.
      */
    public boolean hasProcessortransactionId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'processortransactionId' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder clearProcessortransactionId() {
      processortransactionId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.CharSequence getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder setErrorMessage(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.errorMessage = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder setTimestamp(java.lang.Long value) {
      validate(fields()[5], value);
      this.timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.zaheudev.shared.avro.VoidCompletedEvent.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VoidCompletedEvent build() {
      try {
        VoidCompletedEvent record = new VoidCompletedEvent();
        record.success = fieldSetFlags()[0] ? this.success : (java.lang.Boolean) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.paymentId = fieldSetFlags()[2] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.processortransactionId = fieldSetFlags()[3] ? this.processortransactionId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.errorMessage = fieldSetFlags()[4] ? this.errorMessage : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VoidCompletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<VoidCompletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VoidCompletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<VoidCompletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.success == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.success);
    }

    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status);
    }

    if (this.paymentId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.paymentId);
    }

    if (this.processortransactionId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.processortransactionId);
    }

    if (this.errorMessage == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.errorMessage);
    }

    if (this.timestamp == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.timestamp);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.success = null;
      } else {
        this.success = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.paymentId = null;
      } else {
        this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.processortransactionId = null;
      } else {
        this.processortransactionId = in.readString(this.processortransactionId instanceof Utf8 ? (Utf8)this.processortransactionId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.errorMessage = null;
      } else {
        this.errorMessage = in.readString(this.errorMessage instanceof Utf8 ? (Utf8)this.errorMessage : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.timestamp = null;
      } else {
        this.timestamp = in.readLong();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.success = null;
          } else {
            this.success = in.readBoolean();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.paymentId = null;
          } else {
            this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.processortransactionId = null;
          } else {
            this.processortransactionId = in.readString(this.processortransactionId instanceof Utf8 ? (Utf8)this.processortransactionId : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.errorMessage = null;
          } else {
            this.errorMessage = in.readString(this.errorMessage instanceof Utf8 ? (Utf8)this.errorMessage : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.timestamp = null;
          } else {
            this.timestamp = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (success == null ? 0 : success.hashCode());
    result = 31 * result + (status == null ? 0 : status.hashCode());
    result = 31 * result + (paymentId == null ? 0 : paymentId.hashCode());
    result = 31 * result + (processortransactionId == null ? 0 : processortransactionId.hashCode());
    result = 31 * result + (errorMessage == null ? 0 : errorMessage.hashCode());
    result = 31 * result + (timestamp == null ? 0 : timestamp.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof VoidCompletedEvent)) {
      return false;
    }
    VoidCompletedEvent other = (VoidCompletedEvent) o;
    if (!java.util.Objects.equals(this.success, other.success)) {
      return false;
    }
    if (Utf8.compareSequences(this.status, other.status) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.paymentId, other.paymentId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.processortransactionId, other.processortransactionId) != 0) {
      return false;
    }
    if (Utf8.compareSequences(this.errorMessage, other.errorMessage) != 0) {
      return false;
    }
    if (!java.util.Objects.equals(this.timestamp, other.timestamp)) {
      return false;
    }
    return true;
  }
}










