spring.application.name=demo
server.port=8084
ctm.encryption.secret-key=eventdrivenarchitecturepaymentsy

# Database Configuration (comment out if not using PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/payment-gateway
spring.datasource.username=zaheu
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false